      SUBROUTINE CHLR2S(C,V,N,M)
C BACK SUBSTITUTION AFTER CHOLESKY FACTORIZATION
C SOLUTION OVERWRITES RHS IN V, M=NUMBER OF RHS'S.
      IMPLICIT REAL*8 (A-H,P-Z), INTEGER(o)
      DIMENSION C(1),V(N,M)
      DO 20 MM=1,M
      IC0=0
      DO 10 I=1,N
      CSUM=V(I,MM)
      DO 11 K=1,I-1
  11  CSUM=CSUM-V(K,MM)*C(IC0+K)
      IC0=IC0+I
  10  V(I,MM)=CSUM/C(IC0)

      DO 12 I=N,1,-1
      IND2=(I*(I+1))/2
      CSUM=V(I,MM)
      IND1=IND2+I
      DO 13 K=I+1,N
      CSUM=CSUM-V(K,MM)*C(IND1)
  13  IND1=IND1+K
  12  V(I,MM)=CSUM/C(IND2)
  20  CONTINUE
      RETURN
      END
