      SUBROUTINE CHLR2F(C,W,N,NDEF)
C CHOLESKY FACTORIZATION OF (N X N) REAL*8 MATRIX C.
C RETURNS AS SOON AS MATRIX BECOMES INDEFINITE, REST IS UNCHANGED
C W=WORKSPACE OF DIMENSION N
      IMPLICIT REAL*8 (A-H,P-Z), INTEGER(o)
      DIMENSION C(1),W(N)
      IC0=0
      DO 10 I=1,N
      JC0=0
      DO 11 J=1,I-1
      CSUM=C(IC0+J)
      DO 12 K=1,J-1
  12  CSUM=CSUM-W(K)*C(JC0+K)
      JC0=JC0+J
  11  W(J)=CSUM/C(JC0)
      CSUM=C(IC0+I)
      DO 14 K=1,I-1
  14  CSUM=CSUM-W(K)*W(K)
      IF(CSUM.LE.0.D0) THEN
        NDEF=I-1
        GOTO 99
        ENDIF
      DO 13 J=1,I-1
  13  C(IC0+J)=W(J)
      IC0=IC0+I
  10  C(IC0)=DSQRT(CSUM)
      NDEF=N
  99  IF(NDEF.LT.N) WRITE(6,230) N,NDEF
  230 FORMAT(' CHLR2F:    N=',I4,'    NDEF=',I4)
      RETURN
      END
