      SUBROUTINE DLMTOR(R,A,LMAX,F,FBAR)
C  RADIAL PART OF DAMPED LMTOS F AND FBAR, L=0 TO LMAX
      IMPLICIT REAL*8 (A-H,P-Z), INTEGER(o)
      DIMENSION F(0:LMAX),FBAR(0:LMAX)
      FBSRPI=0.564189835D0
        PI=4.D0*DATAN(1.D0)
        FBSQPI=1.D0/DSQRT(PI)
      Z=A*R


      EMZ2=DEXP(-Z*Z)
      ERFC0=DERFC(Z)
      ERFC1=-Z*ERFC0+FBSRPI*EMZ2
      ERFC2=-0.5D0*Z*ERFC1+0.25D0*ERFC0
      F(0)=ERFC0/R
      FBAR(0)=-ERFC2/(A*A*R)
      TA2R=2.D0*A*A*R
      G=2.D0*A*EMZ2*FBSRPI/R
      FLM2=FBSRPI*EMZ2/Z-ERFC0
      DO 10 L=1,LMAX
      F(L)=((L+L-1)/R)*F(L-1)+G
      FBAR(L)=((L+L-1)/R)*FBAR(L-1)-FLM2
      FLM2=F(L-1)
  10  G=G*TA2R
      RETURN
      END
