      SUBROUTINE HYFIP1(D,D0,A1,MMAX,NDIM,NRHS,NALF,BB,B,
     .    NDIMX,NDIMBX,NRHSX)
C  INTERPOLATES TO GET COEFFS (B) AT DISTANCE D
      IMPLICIT REAL*8 (A-H,P-Z), INTEGER (o)
      DIMENSION NDIM(0:20),NRHS(0:20),F(20),
     .   B(NDIMX,NRHSX,0:MMAX),BB(NDIMBX,NRHSX,0:MMAX)
      CALL GETPR(IPR)
      X=DEXP(A1*(D0-D))
      IF(IPR.GE.30) WRITE(6,440) D,D0,A1,X,NALF
  440 FORMAT(/' HYFIP1:  D=',F9.6,'   D0=',F9.6,'   A1=',F7.4,
     .   '   X=',F9.5,'   NALF=',I2)
      XM=1.D0
      DO 19 IALF=1,NALF
      XM=XM*X
  19  F(IALF)=XM
C ------ ADD TOGETHER FITTED COEFFS ---------------
      DO 10 M=0,MMAX
      ND=NDIM(M)
      NR=NRHS(M)
      DO 10 IR=1,NR
      DO 10 ID=1,ND
      SUM=0.D0
      DO 11 IALF=1,NALF
      IA0=(IALF-1)*ND
  11  SUM=SUM+F(IALF)*BB(ID+IA0,IR,M)
  10  B(ID,IR,M)=SUM
      RETURN
      END
