      SUBROUTINE HYFSRT(MMAX,LX1,NX1,LX2,NX2,LP1,LP2,LSYM,
     .   NDIM,NRHS,BA,BB,NDIMX,NRHSX,NDIMBX,NALF,COFA,NCOF)
C  SORT INTO COLUMNS BY IALF
      IMPLICIT REAL*8 (A-H,P-Z), INTEGER (o)
      DIMENSION NDIM(0:20),NRHS(0:20),COFA(NCOF,NALF),
     .   BA(NDIMX,NRHSX,0:MMAX,NALF),BB(NDIMBX,NRHSX,0:MMAX)
      CALL GETPR(IPR)
C ------- SORT COEFFS INTO BA BY IALF ----------------
      DO 10 M=0,MMAX
      ND=NDIM(M)
      NR=NRHS(M)
      DO 11 IALF=1,NALF
      IA0=(IALF-1)*ND
      DO 11 IR=1,NR
      DO 11 ID=1,ND
  11  BA(ID,IR,M,IALF)=BB(ID+IA0,IR,M)
  10  CONTINUE
C ------- CALL TCFSRT FOR EACH IALF -----------
      DO 20 IALF=1,NALF
      CALL TCFSRT(MMAX,LX1,NX1,LX2,NX2,LP1,LP2,LSYM,NDIM,NRHS,
     .    BA(1,1,0,IALF),NDIMX,NRHSX,COFA(1,IALF))
  20  CONTINUE

      RETURN
      END
