      SUBROUTINE RADINT(R0,A,RMAX,NMAX,R,W,N)
C  POINTS AND WEIGHTS FOR RADIAL INTEGRATION FROM R0 TO INFINITY.
C  POINT SPACING NEAR R0 IS A*R0. RETURNS POINTS SMALLER THAN RMAX.
C  FACTOR R**2 IS NOT INCLUDED.
      IMPLICIT REAL*8 (A-H,P-Z), INTEGER(O)
      DIMENSION R(1),W(1)
      N=DLOG(RMAX/R0)/A+1.D0
      CALL GETPR(IPR)
      IF(IPR.GE.50) WRITE(6,330) R0,A,RMAX,NMAX,N
  330 FORMAT(/' RADINT:  R0=',F8.4,'   A=',F7.3,'   RMAX=',F8.2,
     .   '   NMAX=',I5,'    N=',I5)
      IF(N.GT.NMAX) CALL RX('RADINT: N IS LARGER THAN NMAX''')
      DO 10 I=1,N
      R(I)=R0*DEXP(A*(I-1))
      W1=2.D0*(MOD(I-1,2)+1)
      W(I)=W1*A*R(I)/3.D0
  10  CONTINUE
      W(1)=W(1)*0.5D0
      RETURN
      END
