      SUBROUTINE SETIGV(IVAR,IVAL)
C  SETS INTEGER GLOBAL VARIABLE
      IMPLICIT REAL*8 (A-H,P-Z), INTEGER(o)
      PARAMETER( NX=10 )
      DIMENSION ITBL(NX),LSET(NX)
      SAVE
      DATA LSET /NX*0/
      IF(IVAR.GT.NX.OR.IVAR.LT.1) WRITE(6,*) '*** CANNOT SET GV',IVAR
      IF(IVAR.GT.NX.OR.IVAR.LT.1) RETURN
      ITBL(IVAR)=IVAL
      LSET(IVAR)=1
      RETURN
C -------------------------------------------
      ENTRY GETIGV(IVAR,IVUL)
C  TESTS INTEGER GLOBAL VARIABLE
      IF(IVAR.GT.20.OR.IVAR.LT.1) WRITE(6,*) '*** CANNOT TEST GV',IVAR
      IF(IVAR.GT.20.OR.IVAR.LT.1) RETURN
      IF(LSET(IVAR).EQ.0) THEN
        WRITE(6,*) '*** GETGV: VARIABLE NOT SET, IVAR=',IVAR
        IVUL=0
        RETURN
        ENDIF
      IVUL=ITBL(IVAR)
      RETURN
      END
