      SUBROUTINE TCFDIM(MMAX,LX1,NX1,LX2,NX2,LP1,LP2,LSYM,
     .   NDIM,NRHS,NDIMX,NSDMX,NRHSX,NCOF,NXI)
C  GET DIMENSIONS OF THE M-SPACES, AS WELL AS NUMBER OF RHS.
C  NCOF=TOTAL NUMBER OF COEFFICIENTS.
      IMPLICIT REAL*8 (A-H,P-Z), INTEGER (o)
      DIMENSION NDIM(0:20),NRHS(0:20),LX1(1),LX2(1)
      CALL GETPR(IPR)
C ------ GET NUMBER OF RHS ----------------
      DO 19 M=0,MMAX
  19  NRHS(M)=0.D0
      NF1=0
      DO 20 L1=0,LP1
      DO 20 M1=0,L1
      NF1=NF1+1
      NF2=0
      LTOP=LP2
      IF(LSYM.EQ.1) LTOP=L1
      DO 21 L2=0,LTOP
      MTOP=L2
      IF(LSYM.EQ.1.AND.L2.EQ.L1) MTOP=M1
      DO 21 M2=0,MTOP
      NF2=NF2+1
      MP=M1+M2
      MM=IABS(M1-M2)
      IF(MP.LE.MMAX) NRHS(MP)=NRHS(MP)+1
      IF(MM.NE.MP.AND.MM.LE.MMAX) NRHS(MM)=NRHS(MM)+1
  21  CONTINUE
  20  CONTINUE
C ------ GET NXI ---------------------------------
      NXI=0
      DO 28 I=1,NX1
  28  NXI=NXI+(LX1(I)+1)**2
      DO 29 I=1,NX2
  29  NXI=NXI+(LX2(I)+1)**2
C ------ GET NDIM, NSDM AND PRINTOUT -------------
      NDIMX=0
      NSDMX=0
      NRHSX=0
      NRHST=0
      NCOF=0
      IF(IPR.GE.30) WRITE(6,942)
      DO 10 M=0,MMAX
      ND=0
      DO 12 I=1,NX1
  12  IF(M.LE.LX1(I)) ND=ND+(LX1(I)-M+1)
      DO 13 I=1,NX2
  13  IF(M.LE.LX2(I)) ND=ND+(LX2(I)-M+1)
      NSDM=(ND*(ND+1))/2
      NDIM(M)=ND
      NDIMX=MAX0(NDIMX,NDIM(M))
      NSDMX=MAX0(NSDMX,NSDM)
      NRHSX=MAX0(NRHSX,NRHS(M))
      NRHST=NRHST+NRHS(M)
      IF(IPR.GE.30) WRITE(6,941) M,NDIM(M),NSDM,NRHS(M)
  941 FORMAT(I5,3I10)
  942 FORMAT(/'    M      NDIM      NSDM      NRHS')
  10  NCOF=NCOF+NDIM(M)*NRHS(M)
      IF(IPR.GE.30) WRITE(6,950) NDIMX,NSDMX,NRHSX,NRHST,NCOF,NXI
  950 FORMAT(/' MAX NDIM:',I7,'       MAX NSDM:',I7
     .       /' MAX NRHS:',I7,'       TOT NRHS:',I7
     .       /' TOTAL NUMBER OF NON-ZERO COEFFS:',I7
     .       /' NUMBER OF 3-D FIT FUNCTIONS, XI:',I7)
      RETURN
      END
