      SUBROUTINE TCFSLV(MMAX,S,B,NDIM,NRHS,NDIMX,NSDMX,NRHSX)
C  SOLVE LSQ-FIT PROBLEM FOR TCF. OUTPUT: COEFFS IN B.
      IMPLICIT REAL*8 (A-H,P-Z), INTEGER (o)
      DIMENSION S(NSDMX,0:MMAX),B(NDIMX,NRHSX,0:MMAX),
     .   NDIM(0:20),NRHS(0:20)
      REAL W(1)
      COMMON /W/ W
      CALL GETPR(IPR)
      IF(IPR.GE.40) WRITE(6,940) MMAX
  940 FORMAT(/' TCFSLV:   MMAX=',I3)
      CALL DEFRR(oW,   NDIMX)
C --------- START LOOP OVER M -------------------
      NERR=0
      DO 10 M=0,MMAX
      ND=NDIM(M)
      CALL CHLR2F(S(1,M),W(oW),ND,NDEF)
      IF(IPR.GE.40) WRITE(6,796) M,NRHS(M),ND,NDEF
  796 FORMAT(' M=',I2,'   NRHS=',I4,'    NDIM=',I4,'    NDEF=',I4)
      IF(ND.NE.NDEF) NERR=NERR+1
      DO 11 JRHS=1,NRHS(M)
      CALL CHLR2S(S(1,M),B(1,JRHS,M),ND,1)
      IF(IPR.GE.80) WRITE(6,220) JRHS,(1000*B(I,JRHS,M),I=1,ND)
C|    IF(IPR.GE.30) WRITE(6,220) JRHS,(1000*B(I,JRHS,M),I=1,ND)
  220 FORMAT(' JRHS=',I5/(1X,8F10.5))
  11  CONTINUE
  10  CONTINUE
      IF(NERR.NE.0) CALL RX('TCFSLV:  MATRIX NOT POSITIVE DEFINITE''')
      CALL RLSE(oW)
      RETURN
      END
