% const lmh=f nsp=2 nl=4 ccor=t mode=0 nit=1 nk=8 novmza=f nc=t so=f bf=f idxf=1
% const gamrep=f gfmod=1 scr=0
% const eref=lmh?-2542.34265:-2540.56813
HEADER  Study of iron
VERS    LMASA-6 LM:7 ASA:7
IO      SHOW=F HELP=f VERBOS=31 20 WKP=F IACTIV=t
HAM     NSPIN={nsp} NONCOL={nc|so|bf} BFIELD={bf} SO={so} QASA=0
OPTIONS NSPIN={nsp} LMH={lmh} ASA[ ADNF=f CCOR={ccor} GAMMA={gamrep} ]
        NONCOL={nc|so|bf} SO={so} BFIELD={bf}
        SCR={scr}
% const sdmod=0
        SDYN: f,{sdmod}, {sdmod==0?5/5:10/10},0,0,0,0
TESTDNF cp fe.feso.dnf fe.feso
        lmstr feso >/dev/null
        lm -vso=t -vidxf=2 feso --no-iactiv
TSTLMNC rm -f eula.fe
        lmstr -veulaxy=0 --pr35 fe --iactiv=no -vfile=0 -vnk=24 -vnl=3 -vnc=1 -vbf=0 -vnit=-1
        lm -veulaxy=0 --pr35 fe --iactiv=no -vfile=0 -vnk=24 -vnl=3 -vnc=1 -vbf=0 -vnit=-1
        lm -veulaxy=0 --pr35 fe --iactiv=no -vfile=0 -vnk=24 -vnl=3 -vnc=1 -vbf=0 -vnit=1 --band:fn=syml
        cp bnds.fe bnds-coll.fe
        cp eulaxy.fe eula.fe
        lm -veulaxy=1 --pr35 fe --iactiv=no -vfile=0 -vnk=24 -vnl=3 -vnc=1 -vbf=0 -vnit=1 --band:fn=syml
        cp bnds.fe bndsxy0.fe
        rm -f mixm.fe wkp.fe
        lm -veulaxy=1 --pr35 fe --iactiv=no -vfile=0 -vnk=24 -vnl=3 -vnc=1 -vbf=0 -vnit=-1
        lm -veulaxy=1 --pr35 fe --iactiv=no -vfile=0 -vnk=24 -vnl=3 -vnc=1 -vbf=0 -vnit=1 --band:fn=syml
        cp bnds.fe bndsxy.fe
TSTMPNC rm -f eula.fe
        lmstr -veulaxy=0 --pr35 fe --iactiv=no -vfile=0 -vnk=24 -vnl=3 -vnc=1 -vbf=0 -vnit=-1
        mpirun -n 8 lm -vmet=3 -veulaxy=0 --pr35 fe --iactiv=no -vfile=0 -vnk=24 -vnl=3 -vnc=1 -vbf=0 -vnit=-1
        mpirun -n 8 lm -vmet=3 -veulaxy=0 --pr35 fe --iactiv=no -vfile=0 -vnk=24 -vnl=3 -vnc=1 -vbf=0 -vnit=1 --band:fn=syml
        cp bnds.fe bnds-coll.fe
        cp eulaxy.fe eula.fe
        mpirun -n 8 lm -vmet=3 -veulaxy=1 --pr35 fe --iactiv=no -vfile=0 -vnk=24 -vnl=3 -vnc=1 -vbf=0 -vnit=1 --band:fn=syml
        cp bnds.fe bndsxy0.fe
        rm -f mixm.fe wkp.fe
        mpirun -n 8 lm -vmet=3 -veulaxy=1 --pr35 fe --iactiv=no -vfile=0 -vnk=24 -vnl=3 -vnc=1 -vbf=0 -vnit=-1
        mpirun -n 8 lm -vmet=3 -veulaxy=1 --pr35 fe --iactiv=no -vfile=0 -vnk=24 -vnl=3 -vnc=1 -vbf=0 -vnit=1 --band:fn=syml
        cp bnds.fe bndsxy.fe
GF      MODE={gfmod}
TEST    lmstr feso >/dev/null
        lm -vso=t feso --no-iactiv
CONST   ns=.8 met=1
BZ      NKABC={nk} SAVDOS=F NPTS=1001 PUTQP=f INVIT=F METAL=met
% ifdef so
#        NEVMX=-1 Q=BAND
% endif
        EMESH=12 10 -1 0 .5 .5
STR     RMAX=3.5 MODE={mode}
% ifdef file
% ifdef file>1
STRUC   FILE=site{file} NSPEC=1 NL={nl} ALAT=5.42
SITE    FILE=site{file}
%else
STRUC   FILE=site NSPEC=1 NL={nl} ALAT=5.42
SITE    FILE=site
%endif
SPEC    ATOM=FE Z=26 R/W=1 IDXDN=1,1,1,{idxf} EREF={eref} A=.03 NR=331
        IDMOD=0 0 0 1
% endif
%ifdef eulaxy
SYMGRP  R4Z
%endif
%ifdef nc
SYMGRP  I*I
%endif
STRUC   NBAS=1 NSPEC=1 NL={nl}
        ALAT=5.42 PLAT=  -.5 .5 .5  .5 -.5 .5  .5 .5 -.5
CLASS   ATOM=FE Z=26 R/W=1 IDXDN=1,1,1,{idxf} EREF={eref} A=.03 NR=331
        IDMOD=0 0 0 1
SITE    ATOM=FE POS= 0 0 0 ROT!=(1,.1,.5)0*pi/5
.ITER    MIX=A4,b=.20 NIT={abs(nit)} CONVC=1D-7 CONV=0
.MIX     MODE=A4,b=.20
ITER    MIX=A4,b=.50,w=2,1,n=8;A4,w=1,2,b=.5,k=4 NIT={abs(nit)} CONVC=1D-7 CONV=0
MIX     MODE=A4,b=.50,w=2,1,n=8;A4,w=1,2,b=.5,k=4
ITER    MIX=B NIT={abs(nit)} CONVC=1D-7 CONV=0
MIX     MODE=B
.START   CNTROL=F  BEGMOM=t NIT={abs(nit)} CNVG=1D-7
START   CNTROL={nit<=0} BEGMOM={nit<=0} NIT={nit} CNVG=1D-7
# self-consistent with: lm fe --no-iactiv -vfile=0 -vnk=24 -vnl=3 -vnc=0 -vbf=0 -vnit=-1
        ATOM=FE       P=  4.6642712  4.4032653  3.8676879
                          4.6702754  4.4267924  3.6770409
                      Q=  0.3155211  0.0000000  0.0052616
                          0.3665729  0.0000000  0.0050838
                          4.4581786  0.0000000  0.0447339
                          0.3293462  0.0000000  0.0050506
                          0.4249845  0.0000000  0.0063208
                          2.1053967  0.0000000  0.0116786
# self-consistent with xy orbital (m=-2) spin flipped
# lm -veulaxy=1 --pr35 fe --iactiv -vfile=0 -vnk=24 -vnl=3 -vnc=1 -vbf=0 -vnit=0
%ifdef eulaxy
        ATOM=FE       P=  4.6695019  4.4062437  3.8762673
                          4.6654772  4.4204974  3.6537761
                      Q=  0.3226267  0.0000000  0.0060974
                          0.3676341  0.0000000  0.0054998
                          4.0835687  0.0000000  0.0403339
                          0.3218180  0.0000000  0.0046227
                          0.4156127  0.0000000  0.0059113
                          2.4887398  0.0000000  0.0170484
%endif
