%const  nit=30 begmom=nit<=0
HEADER  Fe 
VERS    LMF-6.10 LMASA-6.10 LM:7 ASA:7
IO      SHOW=F HELP=F VERBOS=31 WKP=F
GF      MODE=1 GFOPTS=emom;p3;padtol=3e-6
%const rel=1 gamma=t so=t twoc=f
CONST   gmax=13 nmix=3 beta=0.5 conv=1d-4 convc=1d-4
        a=2.87/0.529177 nk=16 Rf=0.99 R=Rf*sqrt(3)*a/4
STRUC   NBAS=1 NSPEC=1 NL=5
        ALAT=a PLAT= .5 .5 .5  .5 -.5 .5  .5 .5 -.5
HAM     XCFUN=2 NSPIN=2 REL={rel} NONCOL=F SO={so} QASA=0
OPTIONS NSPIN=2 REL={rel} XCFUN=2 SO={so} SHARM=T NONCOL=F 
        ASA[ GAMMA={gamma} CCOR=f TWOC={twoc} ]
%ifdef sym
SYMGRP  R4Z
%endif
SYMGRP  E
SYMGRP  find
BZ      NKABC=nk TETRA=1 METAL=1 EF0=0 DELEF=0.1 N=1 W=0.02
        NPTS=1001 BZJOB=0 DOS=-1.2 0.5 SAVDOS=1 EFMAX=5 NEVMX=34
% const ef=-0.104583  idmod=0 nr=1501
        EMESH=12 10 {ef-1.0} {ef} 0.5 0.0
SPEC    SCLWSR=1 
        ATOM=A Z=26 R=R IDMOD={idmod} {idmod} {idmod} {idmod} LMX=3 LMXA=3 KMXA=4 LFOCA=1 
        RSMH=R/2 R/2 R/2 R/2 EH=-0.1 -0.1 -0.1 -0.1
        RSMH2=R/2 R/2 R/2 EH2=-1.1 -1.1 -1.1 A=0.01 NR={nr}
        Q=2 0 6 MMOM=0 0 2.2
SITE    ATOM=A POS= 0 0 0
EWALD   TOL=1D-8 NKDMX=1999 NKRMX=1999
ITER    MIX=A3,k=8,b=.5 NIT={abs(nit)} CONVC=1D-6 CONV=0
# ITER    MIX=A3,k=5,b=.2 NIT={abs(nit)} CONVC=1D-6 CONV=0
ITER    MIX=B3,n=5,b=.2 NIT={abs(nit)} CONVC=1D-6 CONV=0
MIX     MODE=B3,n=5,b=1
START   BEGMOM={begmom} CNTROL=F

