#!/bin/csh -f

# This shell script returns a list of routines that must be compiled with
# switches weaker than the standard FFLAGS
# It uses some or all of the following variables to specify the architecture:
#   machine-configuration is the standard GNU format in 'config.sub':
#       CPU_TYPE-MANUFACTURER-KERNEL-OPERATING_SYSTEM
#   machine-mnemonic is the machine mnemonic identified by 'Makemakefile'

if ($#argv != 2) then
  echo usage:  SPECIAL-FLAGS   machine-configuration  machine-mnemonic
  exit -1
endif

set host = $1
set mnemonic = $2

# Separate what the user gave into CPU-COMPANY and OS or KERNEL-OS (if any).
# This is taken from config.sub
set maybe_os = `echo $host | sed 's/^\(.*\)-\([^-]*-[^-]*\)$/\2/'`
switch ($maybe_os)
  case "linux-gnu*":
    set os = $maybe_os
    set basic_machine = `echo $host | sed 's/^\(.*\)-\([^-]*-[^-]*\)$/\1/'`
    breaksw
  default:
    set basic_machine = `echo $host | sed 's/-[^-]*$//'`
    if ( $basic_machine != $maybe_os) then
      set os = `echo $host | sed 's/.*-//'`
    else
      set os
    endif
endsw

# echo $basic_machine $os

# --- Special compilation, FFLAGS_NONE ---
unset lst
if ($mnemonic =~ OSXI) set lst = (pgfasa supgh)
if ($?lst > 0) then
  echo '$(FC) $(FFLAGS_NONE) ::' $lst
endif

# --- Special compilation, FFLAGS_LESS3 ---
unset lst
# if ($basic_machine =~ alphaev6* && $os =~ osf*) set lst = ropyln
# if ($basic_machine =~ alpha-* && $os =~ osf*) set lst = atomsr
if ($?lst > 0) then
  echo '$(FC) $(FFLAGS_LESS3) ::' $lst
endif

# --- Special compilation, FFLAGS_LESS2 ---
unset lst
# if ($os =~ aix*) set lst = (rdccat atomsr secm2c)
# if ($os =~ hpux*) set lst = (radmsh)
# if ($os =~ hpux*) set lst = (radmsh)
# if ($basic_machine =~ mips-sgi) set lst = (npr2tb)
if ($?lst > 0) then
  echo '$(FC) $(FFLAGS_LESS2) ::' $lst
endif

# --- Special compilation, FFLAGS_LESS ---
unset lst
if ($mnemonic == OSXI) set lst = (pgflu)
if ($mnemonic == INTEL_IFORT) set lst = (mkptfp)
# if ($os =~ aix*) set lst = (asa2c)
# if ($os =~ hpux*) set lst = (aiogen conlor salph1 sfill mksoph)
# if ($basic_machine =~ sparc*) set lst = (spcgrp)
if ($?lst > 0) then
  echo '$(FC) $(FFLAGS_LESS) ::' $lst
endif

# --- Other special compilations  ---
# unset lst
# if ($basic_machine =~ *cray*) then
#   if (`uname -m | awk '{print $2}'` == J90) set lst = rdccat
#   if ($?lst > 0) then
#      echo '$(FC) -dp -eRv -Oscalar1,vector1,task0' :: $lst
#   endif
# endif
