#!/bin/tcsh

set lmdir = ~markv/lm
set chk
alias fcda  'f77 -c -ansi \!\!:1-$ |& gawk -v nold=1 -v nnow=1' "'"'{ n2 = nold; nold = nnow ; nnow = $1 != 77 && ! match($0,"lines less|lower-case"); if (nnow && nold && n2 && NF > 0) print $0; prev = $0}'"'"

# --- Start reading switches here ---
options:

  if ( "$1" == "-chk" ) then
    set chk; shift; goto options
  endif

  if ( "$1" == "-s" ) then
    shift; set subs = $1; shift; goto options
  endif

  cd $lmdir
  if ($?subs) then
    if (! -e $subs) goto message
  else
    goto message
  endif

  if ($subs == "main") then

  echo --------------------- main,startup,testing ---------------
  tar cf - main/{lm.f,mkall,Maksmakfile} | ( cd dist ; tar xvf - )
  tar cf - startup | ( cd dist ; tar xvf - )
  chmod 777 dist/testing/gz2Z dist/misc/{eref.dat,cp2dist,Makemakefile}
  rm -f dist/misc/{*~,#*}
  tar cf - testing | ( cd dist ; tar xvf - )

  else
  echo --------------------- $subs ---------------
  cd $subs
#   if (-e Maksmakfile) then
#      echo ... cp Maksmakfile ../dist/$subs
#      cp Maksmakfile ../dist/$subs
#      chmod 755 ../dist/$subs/Maksmakfile
#   endif
  if (-e Special-Flags) then
     echo ... cp Special-Flags ../dist/$subs
     cp Special-Flags ../dist/$subs
     chmod 755 ../dist/$subs/Special-Flags
  endif
#   if (-e INSTALL) then
#      echo ... cp INSTALL ../dist/$subs
#      cp INSTALL ../dist/$subs
#      chmod 755 ../dist/$subs/INSTALL
#   endif
  foreach i ( *.f )
     if (! -e ../dist/$subs/$i) then
       echo new file $i
       cpnone $i ../dist/$subs/$i
       if ($?chk) then
         echo checking compliance with ansi standard "(ftnchek)"
#        echo checking compliance with ansi standard: do f77 -c -ansi $i
         pushd ../dist/$subs/ >/dev/null
#        cat $i| sed 's/_//g' | sed 's/double complex/complex/g' >snot.f; fcda snot.f; if ($status != 0) exit
#        rm snot.f snot.o
         ftnchek -usage=033 -f77=all -nonovice -nosixchar -arguments=1 -truncation=no-type-demotion -f77=no-implicit-none -f77=no-do-enddo -f77=no-double-complex -f77=no-intrinsic $i
         popd >/dev/null
       endif
     else
       set arg2 = `ls -t ../dist/$subs/$i $i`
       if ($arg2[1] !~ ../dist/$subs/$i ) then
         diff -I'implicit none' ../dist/$subs/$i $i >/dev/null
         if ($status != 0) then
           echo 
           echo update $i ... differences:
           diff -I'implicit none' $i ../dist/$subs/$i

           set retval = 1
           if (-e ./ccomp-dist) then
             grep  $i  ./ccomp-dist > /dev/null
             set retval = $status
           endif

           if ($retval == 0) then
             set cccmd = `grep  $i  ./ccomp-dist | head -1`
             echo "ccomp $cccmd"
                   ccomp $cccmd
             cpnone $i~ ../dist/$subs/$i
             rm $i~
           else
             cpnone $i ../dist/$subs/$i
           endif


           if ($?chk) then
               echo checking compliance with ansi standard "(ftnchek)"
#              echo checking compliance with ansi standard: do f77 -c -ansi $i
               pushd ../dist/$subs/ >/dev/null
#              cat $i| sed 's/_//g' >snot.f; fcda snot.f; if ($status != 0) exit
#              rm snot.o snot.f
               ftnchek -usage=033 -f77=all -nonovice -nosixchar -arguments=1 -truncation=no-type-demotion -f77=no-implicit-none -f77=no-do-enddo -f77=no-double-complex -f77=no-intrinsic $i
             popd >/dev/null
           endif
         endif
       endif
     endif
  end
  rm -f ../dist/$subs/snot.o ../dist/$subs/snot.f

  echo --------------------- compare file differences ---------------
  foreach i ( `comp *.f ../dist/$subs ` )
    echo ......... file $i
    diff -I'implicit none' $i ../dist/$subs
  end

  endif

  cd ..
  exit

message:
  echo usage: cp2dist -s subdir
  exit -1


