#!/bin/tcsh
  if ($#argv > 0) goto defaults
message:
  echo  'usage: cpnone [-u] file1 [file2|dir]'
  echo  '              copies file1 to file2, commenting out implicit none'
  echo  '              writes to stdout if file2 missing'
  echo  '              -u uncomments implicit none instead'
  exit -1

# --- Defaults ---
defaults:

#Pick off switches ...
options:
  if ($#argv == 0) goto message
  if (`echo $1 | sed -e 's/\(.\).*/\1/' `  !=  "-") goto end_of_switches

# --- Switches -.... ---
  if ( "$1" == "-u" ) then
    set uncomment; shift; goto options
  endif

# --- End of switches; error if switch not recognized
  goto message
end_of_switches:

  if ($#argv > 2) goto message

  if ($#argv == 2 && $?uncomment) then
    set fn = $2
    if (-d $2) set fn = $2/$1:t
    cat $1 | sed -e 's/^[Cc] *implicit none/      implicit none/' >$fn
  else if ($#argv == 2) then
    set fn = $2
    if (-d $2) set fn = $2/$1:t
    cat $1 | sed -e 's/^ *implicit none/C     implicit none/' >$fn
  else if ($#argv == 1 && $?uncomment) then
    cat $1 | sed -e 's/^[Cc] *implicit none/      implicit none/'
  else if ($#argv == 1) then
    cat $1 | sed -e 's/^ *implicit none/C     implicit none/'
  else
    this should never happen!
  endif


