#! /bin/sh

# A shell script to return a mnemonic for a combination
# of machine hardware and choice of compiler.
# Usage: machine-mnemonic [-FC=fortran-compiler-name] [machine-configuration]
# machine-configuration must be compatible with list in config.sub

# Revisions
#   3 Jul 01  Revised compiler variable from 'F77' to 'FC'

# A table of mnemonics this script knows about (not needed for now)
memlst="DECA LINUXA LINUXF LINUXI LINUX_PGI LINUXPPC SUN-ULTRA AIX90 AIX CONVEX CRAY2 CRAY SGI8 SGIO2 SGI4 HP"

#  for nam in $memlst
#  do
#  echo $nam
#  done

# --- Extract out command-line switches ---
for ac_option
do

# echo ac_option = $ac_option

  case "$ac_option" in
  -*=*) ac_optarg=`echo "$ac_option" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *) ac_optarg= ;;
  esac

  case "$ac_option" in

   -FC=* | --FC=* | -F77=* | --F77=* | -f77=* | --f77=*) FC="$ac_optarg";;

   [A-Za-z0-0]*) host_alias="$ac_option";;

  esac
done

# --- Extract host_alias from config.guess, if not supplied ---
thisdir=`echo $0 | sed s/machine-mnemonic//`
if test -z "$thisdir"; then thisdir=.; fi
if test -z "$host_alias"; then
  host_alias=`$thisdir/config.guess`
fi
# Check validity of host-alias (config.sub)
host=`$thisdir/config.sub "$host_alias"`
if test -z "$host"; then exit -1 ; fi


# --- Try to connect a mnemonic with a machine and compiler name --
case "$host" in

# ... DEC unix machines
  alpha*-dec*)

#   choose a default compiler
    if test -z "$FC"; then FC=f90 ; fi
    case "$FC" in
      f77 | f90) MACH=DECA ;;
      *) echo " *** machine-mnemonic: unrecognized compiler \"$FC\" on machine $host" 1>&2; exit -1 ;;
    esac ;;

# ... DEC alpha running linux
  alpha*-linux*)

#   choose a default compiler
    if test -z "$FC"; then FC=g77 ; fi

    case "$FC" in
     f77 | g77) MACH=LINUXA;;
     fort) MACH=LINUXF;;
     *) echo " *** machine-mnemonic: unrecognized compiler \"$FC\" on machine $host" 1>&2; exit -1 ;;
    esac ;;

  sparc-*-solaris2*)
    MACH=SUN-ULTRA
    ;;

# ... Intel PC running linux
  *i*86-pc*)

    if test -z "$FC"; then FC=g77 ; fi
    case "$FC" in
     f90) MACH=INTEL_IFC;;
     ifc) MACH=INTEL_IFC;;

     pgf77 | pgf90) MACH=LINUX_PGI;;

     f77 | g77) MACH=LINUXI;;

     *) echo " *** machine-mnemonic: unrecognized compiler \"$FC\" on machine $host" 1>&2; exit -1 ;;
    esac ;;

# ... Power PC running linux
   powerpc-*-linux*)
    if test -z "$FC"; then FC=g77 ; fi
    case "$FC" in
     f77 | g77) MACH=LINUXPPC;;
     *) echo " *** machine-mnemonic: unrecognized compiler \"$FC\" on machine $host" 1>&2; exit -1 ;;
    esac ;;

# ... IBM AIX workstations
  *-aix*)
    if test -z "$FC"; then FC=xlf ; fi
    MACH=AIX90
    if test -z "`xlf | grep xlf90 | awk '{print $1}'`"; then MACH=AIX; fi
    ;;

# ... Convex
  *convex*)
    MACH=CONVEX ;;

# ... Cray-2
  cray2-*)
    MACH=CRAY2 ;;

# ... Cray
  *cray*)
    MACH=CRAY ;;

# ... SGI
  *mips-sgi*)

    CPUTYPE=`hinv | grep CPU |head -1 | awk '{print $3}'`
    case "$CPUTYPE" in
      R12000) MACH=SGI8;;

      R10000) IPTYPE=`hinv | egrep '[^M]IP' | sed 's/.*\(IP..\).*/\1/'`
              case "$IPTYPE" in
              IP32) MACH=SGIO2;;
                 *) MACH=SGI8;;
              esac;;

      R8000)  MACH=SGI8;;

      *) MACH=SGI4;;
     esac

    if test -z "$FC"; then FC=f77 ; fi
    case "$FC" in
      f77 | f90) ;;
      *) echo " *** machine-mnemonic: unrecognized compiler \"$FC\" on machine $host" 1>&2; exit -1 ;;
    esac ;;


# ... HP hppa*
  hppa*)
    if test -z "$FC"; then FC=f77 ; fi
    case "$FC" in
      f77 | f90) MACH=HP ;;
      *) echo " *** machine-mnemonic: unrecognized compiler \"$FC\" on machine $host" 1>&2; exit -1 ;;
    esac ;;

  *)
    echo unrecognized machine type ... config aborting
    exit 1
    ;;
esac

echo $MACH
exit 0

