#!/bin/tcsh -f

alias call 'set retcall = \!\!:2 ; set callarg = \!\!:3 ; goto \!\!:1'
set testdir = $TMPDIR
alias zcat 'gunzip -c'
set quiet

while (`echo $1 | sed -e 's/\(.\).*/\1/' `  ==  "-")
  set arg1 = $1; shift

  switch ($arg1)
    case "--verb*":
      unset quiet
      breaksw

    case "--noclean":
      set noclean
      breaksw

    default:
      echo unrecognized switch $arg1
      goto usage
  endsw
end

if ($#argv < 4 | $#argv > 5) goto usage
set at = $1 ; shift

set component = $1 ; shift
if ($component == 'x') then
 set component = 1
else if ($component == 'y') then
 set component = 2
else if ($component == 'z') then
 set component = 3
endif
if ($component == '1' || $component == '2' || $component == '3') then
else
  echo "bad component, $component"
  goto usage
endif

set dp = $1 ; shift

set site_file = $1 ; shift
if (! -r "$site_file") then
  echo shift-site-pos : file \"$site_file\" nonexistent or unreadable
  goto usage
endif

#    awk -v at=$at -v dp=$dp -v c=$component '{if (substr($0,1,1) == "#" || substr($0,1,1) == "%") {print} else {ia += 1 ; if (ia == at) {sub(".*",sprintf("%.8f",dp+$(c+1)),$(c+1))} ; print}}' $site_file
awk -v at=$at -v dp=$dp -v c=$component '{if (substr($0,1,1) == "#" || substr($0,1,1) == "%") {print} else {ia += 1 ; offs = 1 ; if (NF == 3) offs = 0; if (ia == at) {$(c+offs) = sprintf("%.8f",dp+$(c+offs))} ; print}}' $site_file

exit
usage:
echo "usage: shift-site-pos [switches] atom-no component shift site-file [shifted-site-file]"
echo "       reads site-file, shifting one component of one atom's position"
echo "       component must be one of these : x y z 1 2 3"
echo "       switches:"
echo "         (no switches implemented)"
echo "       Example: shift the 3rd component of the 7th atom by -.1, file site.tc"
echo "         shift-site-pos 7 3 -.1 site.tc"
exit
