#!/bin/tcsh

alias call 'set retcall = \!\!:2 ; set callarg = \!\!:3 ; goto \!\!:1'
alias query 'set retcall = \!\!:1 ; set retcall2 = \!\!:2 ; set callarg = \!\!:3 ; goto query'
set slow
set space = '        '

set ftn = fort
set ftn = ifort


if ( $?LIBSLA != 1) then
  echo makedist: no environment variable LIBSLA defined ... aborting
  exit -1
endif

  set nwd = $LIBSLA:h

# --- Start reading switches here ---
options:
  if ( "$1" == "--quiet" ) then
    shift; set quiet; goto options
  endif

  if ( "$1" == "--check" ) then
    shift; set check; goto options
  endif

  if ( "$1" == "--fchk" ) then
    shift; set f90check; goto options
  endif

  if ( "$1" == "--cp" ) then
    shift; set cpf; goto options
  endif

  if ( ! -d $nwd ) then
    echo makedist: missing directory $nwd ... aborting
    exit -1
  endif

  echo ------ check updates in slatsm library in directory $nwd ... -----
  pushd `echo $nwd` >&/dev/null

  foreach i ( startup/* tests/test.slatsm tests/out* tests/t*.f)
    set dest = slatsm/$i 
    if (! -e $dest ) then
      echo new file $i
      if ($?cpf) then
        echo "copy file $i to $dest ?"
        set a = ($<)
        if ($a == "q") exit
        if ($a == "") then
          echo cp $i $dest
               cp $i $dest
        endif
      endif
    else
      set arg2 = `ls -t $dest $i`
      if ($arg2[1] == $i ) then
        echo update $i
	if ($?quiet) then       
	else
	  echo
	  echo ............................................. file $i  ........................
	  echo "$space diff" -I '^C#define .*' -I'implicit none'  $i $dest
	  diff -I '^C#define .*' -I'implicit none'  $i $dest
	  echo ---------
	endif
        if ($?cpf) then
          echo "copy file $i to $dest ?"
          set a = ($<)
          if ($a == "q") exit
          if ($a == "") then
            echo cp $i $dest
                 cp $i $dest
          endif
        endif
      endif
    endif
  end

  foreach i ( *.c *.f)

    set dest = slatsm/$i
    if ($dest:e == f)      set dest = slatsm/$i:r.for

    if (! -e $dest && ! -e slatsm/LAPACK/$i) then
      echo new file $i
      if (! $?quiet) then

        if ($?f90check) then
          echo " "
          echo "$space ... checking file ($ftn)"
          $ftn -g -c -recursive -warn declarations -warn unused $i
          echo "$space ... done compilation"
          echo " "
	endif
        if ($?check) then
          echo " "
          echo "checking compliance with ansi standard (ftnchek)"
          ftnchek -usage=033 -f77=all -nonovice -nosixchar -arguments=1 -truncation=no-type-demotion -f77=no-implicit-none -f77=no-double-complex $i
          echo "$space ... done ftncheck"
          echo " "
        endif

        if ($?cpf) then
          echo "copy file $i to $dest ?"
          set a = ($<)
          if ($a == "q") exit
          if ($a == "") then
#              echo cpnone $i $dest
#                   cpnone $i $dest
             echo cp $i $dest
                  cp $i $dest
          endif
        endif

      endif
    else if (-e slatsm/LAPACK/$i) then
    else
      if (`ls -1t $i $dest | head -1` == "$dest") then
        if (! $?quiet) then
#hhhhhhh           echo ... file $dest newer than file $i ... not checked
        endif
      else
        diff -Iimplicit $i $dest >/dev/null
        if ($status != 0) then

          set retval = 1
          if (-r startup/ccomp-dist) then
            grep  $i:t  startup/ccomp-dist > /dev/null
            set retval = $status
          endif
          if ($retval == 0) then
            set cccmd = `grep  $i:t  startup/ccomp-dist | head -1`
            echo
            echo ............................................. file $i  ........................
            echo "ccomp $cccmd"
          	  ccomp $cccmd
            echo "diff  -I '^C#define .*' -I'implicit none' $i~ $dest"
          	  diff  -I '^C#define .*' -I'implicit none' $i~ $dest | head -60
            rm $i~

          else

            if ($?quiet) then       
              echo file different ... $i
            else

              echo
              echo ............................................. file $i  ........................
              echo "$space diff" -I '^C#define .*'  $i $dest
              diff -I '^C#define .*' $i $dest
              echo ---------
              if ($?f90check) then
                echo " "
                echo "$space ... checking file ($ftn)"
                echo $ftn -g -c -recursive -warn declarations -warn unused $i
                $ftn -g -c -recursive -warn declarations -warn unused $i
                echo "$space ... done compilation"
                echo " "
	      endif
              if ($?check) then
                echo " "
                echo "checking compliance with ansi standard (ftnchek)"
                ftnchek -usage=033 -f77=all -nonovice -nosixchar -arguments=1 -truncation=no-type-demotion -f77=no-implicit-none -f77=no-double-complex $i
                echo "$space ... done ftncheck"
                echo " "
              endif

              if ($?cpf) then
                echo "copy file $i to $dest ?"
                set a = ($<)
                if ($a == "q") exit
                if ($a == "") then
#                    echo cpnone $i $dest
#                         cpnone $i $dest
                  echo cp $i $dest
                       cp $i $dest
                endif
              endif

            endif
          endif
        endif
      endif
    endif

  end
