#!/bin/tcsh -f
# extracts QP levels from spex output

while (`echo $1 | sed -e 's/\(.\).*/\1/' `  ==  "-")
  set arg1 = $1; shift

    case "--vbm=*":
    case "-vbm=*":
      set nvbm=`echo $arg1 | sed s/--vbm=// | sed s/-vbm=//`
      breaksw

    default:
      echo unrecognized switch $arg1
      goto usage
  endsw
end


# File must be present
if ($#argv != 1) goto usage
set outfile = $argv[1]

echo -n '# finding list of QP levels and k-points  (file spexdat1) ...'
catf  -start:s='k-point'  -stop:rel:s=Timing $outfile | grep -v k-point | grep -v Timing | awk '{split($2,a,"[(),]"); print a[2],a[3],a[4], $3}' >spexdat1
set nqp = `wc spexdat1 | awk '{print $1}'`
if ($nqp == 0) then
 echo no k-points found ... aborting
 exit -1
endif
echo " $nqp" levels
 
# Extract K-S energy
grep 'Kohn-Sham     energy' $outfile | awk '{print $4}'  > spexdat2
if (`wc spexdat2 | awk '{print $1}'` != $nqp) then
 echo "file mismatch: list of KS energies different from nqp = $nqp ... aborting"
 exit -1
endif

# Extract H-F energy
grep 'Hartree-Fock  energy' $outfile | awk '{print $5}'  > spexdat3
if (`wc spexdat3 | awk '{print $1}'` != $nqp) then
 echo "file mismatch: list of HF energies different from nqp = $nqp ... aborting"
 exit -1
endif

# Extract QP energy (linearized)
grep 'Quasiparticle correction (linearized)' $outfile | awk '{print $5}'  > spexdat4
if (`wc spexdat4 | awk '{print $1}'` != $nqp) then
 echo "file mismatch: list of QP energies different from nqp = $nqp ... aborting"
 exit -1
endif

grep 'Quasiparticle energy     (linearized)' $outfile | awk '{print $5}'  > spexdat5
if (`wc spexdat5 | awk '{print $1}'` != $nqp) then
 echo "file mismatch: list of QP energies different from nqp = $nqp ... aborting"
 exit -1
endif

# grep 'Quasiparticle correction, Z=1' $outfile | awk '{print $5}'  > spexdat6
# this one for Mark's patch to 2.04
grep 'Quasiparticle correction (lin. / Z=1)' $outfile | awk '{print $7}'  > spexdat6
if (`wc spexdat6 | awk '{print $1}'` != $nqp) then
 echo "file mismatch: list of QP energies different from nqp = $nqp ... aborting"
 exit -1
endif

# this one for Mark's patch to 2.04
#grep 'Quasiparticle energy, Z=1' $outfile | awk '{print $5}'  > spexdat7
grep 'Quasiparticle energy     (lin. / Z=1)' $outfile | awk '{print $7}'  > spexdat7
if (`wc spexdat7 | awk '{print $1}'` != $nqp) then
 echo "file mismatch: list of QP energies different from nqp = $nqp ... aborting"
 exit -1
endif

if ($?nvbm) then
  @ j = `dval $nvbm`
  if ($j <= 0) then
    echo "nvbm = $nvbm doesn't seem to be a positive integer ... aborting"
    exit -1
  endif
  set shftks = -shft=`mc spexdat2 -s-1 -rowl $j | tail -1`
  set shfthf = -shft=`mc spexdat3 -s-1 -rowl $j | tail -1`
  set shfqpz = -shft=`mc spexdat5 -s-1 -rowl $j | tail -1`
  set shfqpz1 = -shft=`mc spexdat7 -s-1 -rowl $j | tail -1`
else
  set shftks
  set shfthf
  set shfqpz
  set shfqpz1
endif

  echo '#    ehk        dSE      QP      dSE(Z=1)  QP(Z=1)       HF                  qp             band'
  mc -ff9.4,2x,2f9.4,2x,2f9.4,2x,f9.4,2x,3f9.4,f6.0 spexdat2 $shftks  spexdat4 -ccat spexdat5 $shfqpz -ccat spexdat6 -ccat spexdat7 $shfqpz1 -ccat \
  spexdat3 $shfthf -ccat spexdat1 -ccat | sed 's/\.$//' | grep -v rows

exit
usage:
echo "usage : $0 [--switches] outfile"

echo '        switches:'
echo '          --help'
echo '          --h'
echo '            show this message'

echo ' '
echo '          --vbm=#'
echo '          -vbm=#'
echo '            Use this QP as the energy 0'


