#!/bin/tcsh -f

# echo "("`infgw | grep nbloch | grep -v nblocha | awk '{printf "nbloch=%d\n",$1}'`,`grep Makidx llmfgw01 | awk '{printf "ndimh=%d\n",$8}'`,time=`tail -3 lx0 | grep Wall | awk '{printf "%.0f\n",$6}'`+`tail -3 lsc  | grep Wall | awk '{printf "%.0f\n",$6}'`,`uname -m`')'

set wt
# set CPUid = X5650-2.67
# Works for Linux machines and Intel processors
if (! $?CPUid) then
  set CPUid = `cat /proc/cpuinfo | grep 'model name' | tail -1 | sed s'/CPU\|GHz//g' | awk '{printf "%s-%s\n", $6,$NF}'`
endif

while (`echo $1 | sed -e 's/\(.\).*/\1/' `  ==  "-")
  set arg1 = $1; shift

  switch ($arg1)
    case "--wt=*":
      set wt = `echo $arg1 | sed s/--wt=//`
#      set wt = `grep 'exit with wall clock time' $wt  | tail -1 | awk '{print $NF}' | sed 's/(/(wall=/'`
      set wt = `grep 'exit with wall clock time' $wt  | tail -1 | awk '{print $NF}' `
      breaksw

    case "--spex":
    case "-spex":
    case "--spexi":
    case "-spexi":
      set spex = 1
      breaksw

    case "--spexf":
    case "-spexf":
    case "--spexfi":
    case "-spexfi":
      set spex = 1
      set fleur = 1
      breaksw

    default:
      echo unrecognized switch $arg1
      goto usage
  endsw
end


if ($?spex) then  # spex calculation

  set nprod = `grep 'Total number of product-basis functions:' lspex  | awk '{print $NF}'`
  set ngvec = `grep 'Maximal number of G vectors:' lspex  | awk '{print $NF}'`
  set nprodr = `grep 'Order of array suscep:' lspex | sort | tail -1 | awk '{print $NF}'`
  set nband = `grep 'Number of bands:' lspex  | awk '{print $NF}'`
  set tims = `grep Timing: lspex  | tail -1 | awk '{print $NF}'`
  if ($tims < 600) then
    set tim = `dval -fd1 $tims/60`m
  else
    set tim = `dval -fd0 $tims/60`m
  endif

#   if ($?fleur) then
#     set nband = `grep 'Number of bands:' lspex  | awk '{print $NF}'`
#   endif

  echo "(mbas=$ngvec+$nprod,$nprodr,nband=$nband,time=$tim,$CPU)"

else

grep -v 'npw = ' llmfgw00 |  grep 'ndham = ' >/dev/null
if (! $status) then
  set ndham = `grep 'ndham = ' llmfgw00 | awk '{if ($12 == "ndham") printf "%d\n",$14}'`
  set nlmto = `grep Makidx llmfgw00 | awk '{printf "%d",$8}'`
  @ npw = $ndham - $nlmto

  echo -n "("`infgw | grep nbloch | grep -v nblocha | awk '{printf "nbloch=%d\n",$1}'`"("`infgw | grep nblocha | head -1 | awk '{print $1}'`")",$nlmto{+}$npw,time=`tail -3 lx0 | grep Wall | awk '{printf "%.0f\n",$6}'`+`tail -3 lsc  | grep Wall | awk '{printf "%.0f\n",$6}'`')'

else

  set ndim = `grep Makidx llmfgw00 | awk '{printf "ndimh=%d\n",$8}'`{}`grep 'npw =' llmfgw00 | awk '{if ($11 == "npw") printf "+%d\n",$13}'`
  echo -n "("`infgw | grep nbloch | grep -v nblocha | awk '{printf "nbloch=%d\n",$1}'`"("`infgw | grep nblocha | head -1 | awk '{print $1}'`")",$ndim,time=`tail -3 lx0 | grep Wall | awk '{printf "%.0f\n",$6}'`+`tail -3 lsc  | grep Wall | awk -vcpuid=$CPUid '{printf "%.0fm%s,%s\n",$6,wt,cpuid}'`')'

endif

endif

if (`grep 'Max alloc:' lsc | wc | awk '{print $1}'` > 0) then
  echo -n   "  Max alloc:  lx0"  `grep 'Max alloc:' lx0 | tail -1 | awk '{printf "%i", $NF}'`
  echo -n   "  lsc"  `grep 'Max alloc:' lsc | tail -1 | awk '{printf "%i", $NF}'`
else if (`grep 'Max dynamic allocation' lsc | wc | awk '{print $1}'` > 0) then
  echo -n   "  Max alloc:  lx0"  `grep 'Max dynam' lx0  | awk '{printf "%i\n", $(NF-1)}' | head -1` 
  echo -n   "  lsc"  `grep 'Max dynam' lsc  | awk '{printf "%i\n", $(NF-1)}' | head -1`
endif
echo ""
