#! /bin/tcsh
# extracts data from QPU and other files.

while (`echo $1 | sed -e 's/\(.\).*/\1/' `  ==  "-")
  set arg1 = $1; shift

  switch ($arg1)
    case "--efile":
      set efile
      breaksw

    case "--qpu":
      set qpu
      breaksw

    case "--sc":
      set sc
      breaksw

    default:
      echo unrecognized switch $arg1
      goto usage
  endsw
end

if (! $?qpu && ! $?efile && ! $?sc) then
echo '--- eQP  eShift  eQP(noZ) eShift   eLDA       q                ib'
else if (! $?qpu && ! $?efile) then
echo '--- eQP  eShift        q                ib'
endif

set fn = QPU
if (-e QP) set fn = QP
if ($?efile) then
set fn = TOTE2.UP
if (-e TOTE2) set fn = TOTE2
endif

if (! $?sc) then

if ($?efile) then
cat $fn | sed s/D-/E-/g | sed s/D+/E+/g | awk '{if(NF>8){printf "%7.3f %7.3f %7.3f %7.3f %7.3f     %5.2f %5.2f %5.2f %3d \n", $7,$7-$6,$8,$8-$6,$6,$1,$2,$3,$4 }}'
else
echo '#  eQP     dSE    eQPZ1   dSEZ1    eH0              q         band'
cat $fn | awk '{if(NF>15){printf "%7.2f %7.2f %7.2f %7.2f %7.2f     %5.2f %5.2f %5.2f %3d \n",  \
                      $12,$9,$13,$10,$11,$1,$2,$3,$4 };     \
                      if(NF==0){printf "\n"}}'
endif

else

cat $fn | awk '{if(NF>15){printf "%7.2f %7.2f      %5.2f %5.2f %5.2f %3d \n",  \
                      $11,$10,$1,$2,$3,$4 };     \
                      if(NF==0){printf "\n"}}'

endif

if ($?qpu || $?efile) then
exit
endif

echo ' --- parameters ---- '
head -1 hbe.d |awk '{printf " %9d ",$6}'          ;echo ' = nband'
head -1 hbe.d |awk '{printf " %9d ",$4}'          ;echo ' = lmto augmentation channels'
grep ^dw GWinput | sed s/D-/E-/g | sed s/D+/E+/g | awk '{printf " %9.4f ",$2}';echo ' = dw a.u.'
grep ^niw GWinput | sed s/D-/E-/g | sed s/D+/E+/g | awk '{printf " %9d ",$2}';echo ' = niw'
grep ^deltaw GWinput | sed s/D-/E-/g | sed s/D+/E+/g | awk '{printf " %9.4f ",$2}';echo ' = deltaw a.u.'
grep ^esmr GWinput | sed s/D-/E-/g | sed s/D+/E+/g | awk '{printf " %9.4f ",$2}';echo ' = esmr Ry'
grep -A 2 '<PRODUCT_BASIS>' GWinput | tail -1 | sed s/D-/E-/g | sed s/D+/E+/g | awk '{printf " %9.5f ",$1}'  ;echo ' = tolerance for p-basis '
grep -A 4 '<PRODUCT_BASIS>' GWinput | tail -1 | sed s/D-/E-/g | sed s/D+/E+/g | awk '{printf " %9d ",$1}'    ;echo ' = lcutmx '
grep ^n1n2n3 GWinput |awk '{printf " %3d%3d%3d ",$2,$3,$4}'  ;echo ' = n1 n2 n3 '
grep ^QpGcut_psi GWinput | sed s/D-/E-/g | sed s/D+/E+/g | awk '{printf " %9.2f ",$2}';echo ' = |q+G|max for phi '
grep ^QpGcut_cou GWinput | sed s/D-/E-/g | sed s/D+/E+/g | awk '{printf " %9.2f ",$2}';echo ' = |q+G|max for Vcou '
# head -3  GWIN_V2 |tail -1|awk '{printf " %9.4f ",$1}';echo ' = dw a.u. '
# head -5  GWIN_V2 |tail -1|awk '{printf " %9d ",$1}'  ;echo ' = niw '
# head -9  GWIN_V2 |tail -1|awk '{printf " %9.4f ",$1}'  ;echo ' = deltaw a.u. '
# head -11 GWIN_V2 |tail -1|awk '{printf " %9.4f ",$1}'  ;echo ' = esmr Ry '
# head -2 GWIN0 |tail -1|awk '{printf " %3d%3d%3d ",$1,$2,$3}'  ;echo ' = n1 n2 n3 '
# head -4 GWIN0 |tail -1|awk '{printf " %9.2f ",$1}' ;echo ' = |q+G|max for phi '
# head -4 GWIN0 |tail -1|awk '{printf " %9.2f ",$2}' ;echo ' = |q+G|max for Vcou '
# head -17 GWIN_V2 |tail -1|awk '{printf " %9.5f ",$1}'  ;echo ' = tolerance for p-basis '
# head -19 GWIN_V2 |tail -1|awk '{printf " %9d ",$1}'    ;echo ' = lcutmx '
grep frhis lx0 >/dev/null
if ($status == 0) then
  grep frhis lx0 | awk '{printf " %9d  = number of points on real energy axis\n",$5}'
endif

grep nbloch lsc | sed s/ngc=// |head -1  |awk '{printf " %9d  = nblocha\n %9d  = ngc \n %9d  = nbloch\n",$6,$8,$6+$8}'
grep nblocha lbas |awk '{printf "    %9d = nblocha \n",$6}'    ;
tail -1 lx0 |awk '{printf " %9.1f min = %.1fh for lx0 \n" ,$4,$4/60}'
tail -1 lsc |awk '{printf " %9.1f min = %.1fh for lsc \n" ,$4,$4/60}'
grep shift $fn |awk '{printf " %9.4f  = E_shift eV\n",$3}'    ;
echo -n `sum ctrl.* | awk '{print $1}'`; echo ' = sum check of ctrl.* '
echo -n `sum rst.*  | awk '{print $1}'`; echo ' = sum check of rst.* '



exit
usage:
echo 'usage : infgw [--qpu] [--sc]'
echo '        extracts information from QPU file.'
echo '        infgw uses the following files:'
echo '          QP|QPU hbe.d GWIN0 GWIN_V2 lx0 lsx lsc lbas'
echo ' '
echo '        For QP levels, file QP is used, if it exists; else file QPU is used'
echo ' '
echo '        switches:'
echo '        --qpu   only extracts QP levels from QP or QPU file'
echo '                ... no other information printed or files needed'
echo ' '
echo '        --efile  only extracts QP levels from TOTE2 or TOTE2.UP file'
echo '                ... no other information printed or files needed'
echo ' '
echo '        --sc    QPU file output of self-consistent calculation'
echo '                ... only one column is extracted'


