#! /bin/tcsh
set prog = $0:t

set clean ; set veryclean; set tosetup

while ($#argv > 0)
  switch ($1)
    case --h:
      goto message

    case --help:
      goto message

    case --clean:
      set clean ; shift; breaksw

    case --veryclean:
      set clean ; set veryclean; shift; breaksw

    case --tosetup=no:
      unset tosetup; shift; breaksw

    case --tosetup:
      set clean ; set veryclean; set tosetup; shift; breaksw

    case -*:
      echo "$prog (aborting): unrecognized switch $1"
      exit -1

    default:
      set ext = $1 ; shift; breaksw
  endsw
end

touch PPOVLI.1
rm -f PPOVL PPOVL0 PPOVLI.* PPOVLGG
rm -f BZDATA QBZ
rm -f CphiGeig HAMindex
touch VCCFP; rm -f VCC*
rm -f PLN
touch WVR.; rm -f WVR.*
touch WVI.; rm -f WVI.* W0W0I EPSwklm
touch PPOVLG.001; rm -f PPOVLG.*
touch PPBRD; rm -f PPBRD*
touch BASFP01; rm -f BASFP*
touch Vcoud.00001; rm -f Vcoud.*

rm -f EPS0inv
rm -f HVCCIN
rm -f GEIG
touch PHI; rm -f PHI*
rm -f CPHI
rm -f EValue EVD EVU
rm -f VXCFP
rm -f eigmtet mtet Qeigval
rm -f VXCFPV
rm -f normchk.dia normchk.off mpiqlst
rm -f genallcft3.dump
rm -f genallcf3.dump
rm -f DATA4GW_V2
rm -f evec_prev_iter evec v_xc
touch VXCFP.chk; rm -f *.chk
rm -f NBANDikp Mix0vec1 vxc

if ($?ext) then
  touch normchk.$ext normchk.$ext{}_1
  rm -f normchk.$ext normchk.$ext{}_*
  touch evec.$ext evec.$ext{}_1
  rm -f evec.$ext evec.$ext{}_*
  rm -f ham.$ext
  touch vxc.$ext vxc.$ext{}_1
  rm -f vxc.$ext vxc.$ext{}_*
  touch gw1.$ext gw1.$ext{}_1
  rm -f gw*.$ext gw*.$ext{}_*
  touch rhoMT.1
  rm -f rhoMT.*
endif

if ($?clean) then
  rm -f lqg4gw llmfgw01 llmf2gw lrdata4gw leftet lchknw lbasC lvccC lsxC lbas lvcc lsx lx0 lsc lqpe ldima
  rm -f @MNLA_core @MNLA_CPHI NLAindx evec0
  if ($?ext) then
     rm -f normchk.$ext evec.$ext ham.$ext
  endif
endif

if ($?veryclean) then
  rm -f NW EFERMI EFERMI.check  EFERMI.QP  EFERMI.QPz=1 EFCLASSin ECORE CLASS LMTO WV.d KPTin1BZ LATTC QGcou QGpsi SYMOPS hbe.d frhis_m Mix0vec
  rm -f DOSACC.lda DOSACC2.lda dat.tmp1 dat.tmp2 emesh.hsfp0 emesh.hx0fp0 freq_r v_xc
  touch TOTE XC SE
  rm -f TOTE*
  rm -f XC*
  rm -f SE*
endif

if ($?tosetup) then
  rm -f Q0P QPU QPD NQIBZ QIBZ dat dat2 mixsigma 
  if ($?ext) then
     rm -f vxc.$ext moms.$ext mixm.$ext save.$ext wkp.$ext ctrl.preprocessed.$ext 
  endif
endif

exit 0

message:
  echo  "usage: $prog [--switches] [ext]"
  echo  "       optional ext removes files gw*.ext"
  echo  "       switches:"
  echo  "         --clean     also removes files DATA4GW, *.chk, NW, l*"
  echo  "         --veryclean also removes files NW EFERMI EFCLASSin ECORE CLASS LMTO TOTE* WV.d hbe.dlm"
  echo  "                     KPTin1BZ LATTC QGcou QGpsi SYMOPS XC* SE* DOSACC.lda DOSACC2.lda"
  echo  "                     normchk.ext"
  echo  "         --tosetup   also removes files QPU QPD NQIBZ dat"

  exit -1
endif
