rdcmd:  lmstr fe
 -----------------------  START LMSTR -----------------------
 HEADER Study of iron

 LMSTR:    nbas = 1  nspec = 1  vn 7.11.d  verb 31,20
 special

                Plat                                  Qlat
  -0.500000   0.500000   0.500000        0.000000   1.000000   1.000000
   0.500000  -0.500000   0.500000        1.000000   0.000000   1.000000
   0.500000   0.500000  -0.500000        1.000000   1.000000   0.000000
   alat = 5.406  Cell vol = 78.994732

 LATTC:  as= 2.000   tol=1.00E-08   alat= 5.40600   awald= 0.466
         r1=  2.467   nkd= 137      q1=  4.689   nkg= 201

 SGROUP: 48 symmetry operations from 3 generators
 MKSYM:  found 48 space group operations ... includes inversion

 ASASTR: strux for 2nd gen LMTOs, and Sdot
         avw = 2.661766

 pairc, ib=  1:  51 neighbors in range  1.723*alat =   9.32
 pairc:  51 pairs total  51 is max cluster size
 strscr:  generated 51 inequivalent strux from 51 total
 Exit 0 LMSTR 
 CPU time:    0.050s   Wall clock    0.091s   11:22:36 18.12.2014        on phpdl1.ph.kcl.ac.uk
rdcmd:  lm -vnit=0 -vnk=6 fe --no-iactiv
 -----------------------  START LM -----------------------
 HEADER Study of iron

 LM:       nbas = 1  nspec = 1  vn 7.11.d  verb 31,20
 special
 pot:      spin-pol, XC:BH
 bz:       metal, tetra 

                Plat                                  Qlat
  -0.500000   0.500000   0.500000        0.000000   1.000000   1.000000
   0.500000  -0.500000   0.500000        1.000000   0.000000   1.000000
   0.500000   0.500000  -0.500000        1.000000   1.000000   0.000000
   alat = 5.406  Cell vol = 78.994732

 LATTC:  as= 2.000   tol=1.00E-08   alat= 5.40600   awald= 0.466
         r1=  2.467   nkd= 137      q1=  4.689   nkg= 201

 SGROUP: 48 symmetry operations from 3 generators
 MKSYM:  found 48 space group operations ... includes inversion
 BZMESH:  16 irreducible QP from 216 ( 6 6 6 )  shift= F F F
 TETIRR: sorting 1296 tetrahedra ... 191 inequivalent ones found

 GETZV:  8 valence electrons
ATOM=FE   Z=26  Qc=18  R=2.661766  Qv=0  mom=-2.30148  a=0.012  nr=827

 Class        Qtot       Qbak       Vmad     Vh(Rmax)    V(Rmax)
 FE         0.000000   0.000000   0.000000   0.000000  -0.767540
 Sum Q=0.000000  Emad=0.000000(0.000000)  Vmtz=-0.767540 (up-dn=-0.014189)
 LM: it 0 of 0  ehk0=-0.465080  pv=-0.0634  mmom=-2.3015  seref=-2540.56813
 cpudel    ...   Time this iter:  time(s):  0.198    total:  0.198s
 Exit 0 LM 
 CPU time:    0.198s   Wall clock    0.238s   11:22:37 18.12.2014        on phpdl1.ph.kcl.ac.uk
rdcmd:  lm fe -vnk=16 --no-iactiv -vlteto=3 -voptmod=-5 -vlpart=2 --quit=band --jdosw~5,6,8 --jdosw2~7,9
 -----------------------  START LM -----------------------
 HEADER Study of iron

 LM:       nbas = 1  nspec = 1  vn 7.11.d  verb 31,20
 special:  sharm
 pot:      spin-pol, XC:BH
 optics:   DOS, k-decomp, 1001 pts in [-1,0.5]
 bz:       metal, tetra 

                Plat                                  Qlat
  -0.500000   0.500000   0.500000        0.000000   1.000000   1.000000
   0.500000  -0.500000   0.500000        1.000000   0.000000   1.000000
   0.500000   0.500000  -0.500000        1.000000   1.000000   0.000000
   alat = 5.406  Cell vol = 78.994732

 LATTC:  as= 2.000   tol=1.00E-08   alat= 5.40600   awald= 0.466
         r1=  2.467   nkd= 137      q1=  4.689   nkg= 201

 SGROUP: 48 symmetry operations from 3 generators
 MKSYM:  found 48 space group operations ... includes inversion
 BZMESH:  145 irreducible QP from 4096 ( 16 16 16 )  shift= F F F
 TETIRR: sorting 24576 tetrahedra ... 4715 inequivalent ones found

 GETZV:  8 valence electrons

 Class        Qtot       Qbak       Vmad     Vh(Rmax)    V(Rmax)
 FE         0.000000   0.000000   0.000000   0.000000  -0.767540
 Sum Q=0.000000  Emad=0.000000(0.000000)  Vmtz=-0.767540 (up-dn=-0.014189)
 cpudel    ...   Time this iter:  time(s):  0.108    total:  0.108s

 Makidx:  hamiltonian dimensions Low, Int, High, Negl: 9 0 0 0

 --- BNDASA : iteration 1 (KKR-qout) ---
 (warning, optics) first empty state (#1) below first filled state (#2)

 BNDASA:  Mulliken projection of JDOS 
          group:  3 channel(s): 5,6,8 (occ)  
          grp 2:  2 channel(s): 7,9 (occ)  

 subzi: tetrahedron integration of bands; tetrahedron integration of density

 SECMAT:  kpt 1 of 145, k=  0.00000  0.00000  0.00000
 -0.6663 -0.0617 -0.0617 -0.0617  0.0495  0.0495  2.4838  2.4838  2.4838
 SECMAT:  kpt 1 of 145, k=  0.00000  0.00000  0.00000
 -0.6965 -0.2191 -0.2191 -0.2191 -0.1178 -0.1178  2.4160  2.4160  2.4160
 SECMAT:  kpt 101 of 145, k=  0.68750  0.75000  1.18750
 -0.2141 -0.1863 -0.1219  0.0520  0.0976  0.4355  0.6822  0.8557  1.8987
 SECMAT:  kpt 101 of 145, k=  0.68750  0.75000  1.18750
 -0.3268 -0.2995 -0.2598 -0.1134 -0.0731  0.3319  0.5831  0.7737  1.8415

 BZWTS : --- Tetrahedron Integration ---
 BZINTS: Fermi energy:     -0.050936;   8.000000 electrons;  D(Ef):   15.305
         Sum occ. bands:   -1.7130908  incl. Bloechl correction:   -0.001166
         Mag. moment:      -2.285556

 Saved qp weights ...

 OPTINQ:  DOS from occ bands (2,9), 2 Mulliken projection(s)
          Resolve by k
          1001 points in energy window (-1.0,0.5)  Efermi=-0.050936
          Reduce bands to range (2,5)
 TETWTQ:  total number of (occ,unocc) pairs = 20443, 5 or fewer per qp
 OPTINT:  writing jdos file ...
          writing ascii file popt:  145 channels, 3 polarizations

 ... Generating total DOS

 LM: ehf=-0.4639695  ehk=-0.4639701  sumev=-1.7130908  delsev=0.0011104
h nk=16 lteto=3 optmod=-5 lpart=2 mmom=-2.285556 ehf=-.4639695 ehk=-.4639701
 Exit 0 LM      : quit after bands 
 CPU time:    0.746s   Wall clock    0.786s   11:22:37 18.12.2014        on phpdl1.ph.kcl.ac.uk
rdcmd:  mv jdos.fe jdos-spin1.fe
rdcmd:  lm -vnit=0 -vnk=6 fe --no-iactiv
 -----------------------  START LM -----------------------
 HEADER Study of iron

 LM:       nbas = 1  nspec = 1  vn 7.11.d  verb 31,20
 special
 pot:      spin-pol, XC:BH
 bz:       metal, tetra 

                Plat                                  Qlat
  -0.500000   0.500000   0.500000        0.000000   1.000000   1.000000
   0.500000  -0.500000   0.500000        1.000000   0.000000   1.000000
   0.500000   0.500000  -0.500000        1.000000   1.000000   0.000000
   alat = 5.406  Cell vol = 78.994732

 LATTC:  as= 2.000   tol=1.00E-08   alat= 5.40600   awald= 0.466
         r1=  2.467   nkd= 137      q1=  4.689   nkg= 201

 SGROUP: 48 symmetry operations from 3 generators
 MKSYM:  found 48 space group operations ... includes inversion
 BZMESH:  16 irreducible QP from 216 ( 6 6 6 )  shift= F F F
 TETIRR: sorting 1296 tetrahedra ... 191 inequivalent ones found

 GETZV:  8 valence electrons
ATOM=FE   Z=26  Qc=18  R=2.661766  Qv=0  mom=-2.30148  a=0.012  nr=827

 Class        Qtot       Qbak       Vmad     Vh(Rmax)    V(Rmax)
 FE         0.000000   0.000000   0.000000   0.000000  -0.767540
 Sum Q=0.000000  Emad=0.000000(0.000000)  Vmtz=-0.767540 (up-dn=-0.014189)
 LM: it 0 of 0  ehk0=-0.465080  pv=-0.0634  mmom=-2.3015  seref=-2540.56813
 cpudel    ...   Time this iter:  time(s):  0.119    total:  0.119s
 Exit 0 LM 
 CPU time:    0.119s   Wall clock    0.160s   11:22:37 18.12.2014        on phpdl1.ph.kcl.ac.uk
rdcmd:  lm fe -vnk=16 --no-iactiv -vlteto=3 -voptmod=-6 -vlpart=2 --quit=band --jdosw~5,6,8 --jdosw2~7,9
 -----------------------  START LM -----------------------
 HEADER Study of iron

 LM:       nbas = 1  nspec = 1  vn 7.11.d  verb 31,20
 special:  sharm
 pot:      spin-pol, XC:BH
 optics:   DOS, k-decomp, 1001 pts in [-1,0.5]
 bz:       metal, tetra 

                Plat                                  Qlat
  -0.500000   0.500000   0.500000        0.000000   1.000000   1.000000
   0.500000  -0.500000   0.500000        1.000000   0.000000   1.000000
   0.500000   0.500000  -0.500000        1.000000   1.000000   0.000000
   alat = 5.406  Cell vol = 78.994732

 LATTC:  as= 2.000   tol=1.00E-08   alat= 5.40600   awald= 0.466
         r1=  2.467   nkd= 137      q1=  4.689   nkg= 201

 SGROUP: 48 symmetry operations from 3 generators
 MKSYM:  found 48 space group operations ... includes inversion
 BZMESH:  145 irreducible QP from 4096 ( 16 16 16 )  shift= F F F
 TETIRR: sorting 24576 tetrahedra ... 4715 inequivalent ones found

 GETZV:  8 valence electrons

 Class        Qtot       Qbak       Vmad     Vh(Rmax)    V(Rmax)
 FE         0.000000   0.000000   0.000000   0.000000  -0.767540
 Sum Q=0.000000  Emad=0.000000(0.000000)  Vmtz=-0.767540 (up-dn=-0.014189)
 cpudel    ...   Time this iter:  time(s):  0.108    total:  0.108s

 Makidx:  hamiltonian dimensions Low, Int, High, Negl: 9 0 0 0

 --- BNDASA : iteration 1 (KKR-qout) ---
 (warning, optics) first empty state (#1) below first filled state (#2)

 BNDASA:  Mulliken projection of JDOS 
          group:  3 channel(s): 5,6,8 (occ)  
          grp 2:  2 channel(s): 7,9 (occ)  

 subzi: tetrahedron integration of bands; tetrahedron integration of density

 SECMAT:  kpt 1 of 145, k=  0.00000  0.00000  0.00000
 -0.6663 -0.0617 -0.0617 -0.0617  0.0495  0.0495  2.4838  2.4838  2.4838
 SECMAT:  kpt 1 of 145, k=  0.00000  0.00000  0.00000
 -0.6965 -0.2191 -0.2191 -0.2191 -0.1178 -0.1178  2.4160  2.4160  2.4160
 SECMAT:  kpt 101 of 145, k=  0.68750  0.75000  1.18750
 -0.2141 -0.1863 -0.1219  0.0520  0.0976  0.4355  0.6822  0.8557  1.8987
 SECMAT:  kpt 101 of 145, k=  0.68750  0.75000  1.18750
 -0.3268 -0.2995 -0.2598 -0.1134 -0.0731  0.3319  0.5831  0.7737  1.8415

 BZWTS : --- Tetrahedron Integration ---
 BZINTS: Fermi energy:     -0.050936;   8.000000 electrons;  D(Ef):   15.305
         Sum occ. bands:   -1.7130909  incl. Bloechl correction:   -0.001166
         Mag. moment:      -2.285556

 Saved qp weights ...

 OPTINQ:  DOS (spin 2) from occ bands (2,9), 2 Mulliken projection(s)
          Resolve by k
          1001 points in energy window (-1.0,0.5)  Efermi=-0.050936
          Reduce bands to range (2,6)
 TETWTQ:  total number of (occ,unocc) pairs = 21251, 6 or fewer per qp
 OPTINT:  writing jdos file ...
          writing ascii file popt:  145 channels, 3 polarizations

 ... Generating total DOS

 LM: ehf=-0.4639692  ehk=-0.4639701  sumev=-1.7130909  delsev=0.0011104
h nk=16 lteto=3 optmod=-6 lpart=2 mmom=-2.285556 ehf=-.4639692 ehk=-.4639701
 Exit 0 LM      : quit after bands 
 CPU time:    0.795s   Wall clock    0.835s   11:22:38 18.12.2014        on phpdl1.ph.kcl.ac.uk
