% const ccor=f twoc=f nk=16 gfmod=1 ldau=0 met=ldau?3:1
# To plot SWs in meV:
# echo 0,500,5,10 | plbnds -fplot -scl=13.6 -lbl=G,H,N,P,G,N  bnds.fe
HEADER  Study of Fe
VERS    LMASA-6 LM:7 ASA:7
IO      SHOW=F HELP=f VERBOS=31 20 WKP=F IACTIV=t TIM=f
% const sharm=0 sx=0
OPTIONS NSPIN=2 NONCOL=f SHARM={sharm} SX={sx}
        ASA[ CCOR={ccor} TWOC={twoc} GAMMA=t ]
SYMGRP  R4X MX R3D
BZ      NKABC={nk} SAVDOS=F NPTS=501 NEVMX=18 EFMAX=9 PUTQP=f
        TETRA=1 METAL={met} INVIT=F
        EMESH=12 10 -1 0 .5 .5
% const ef=-0.0538183
        EMESH=12+1 2 {ef} {ef+.004*12} .001
GF      MODE={gfmod} GFOPTS=p3
% const rmaxs=3.5
STR     RMAX={rmaxs} MODE=0
CLASS   ATOM=A Z=26 R/W=1 IDXDN=0 0 0 2 EREF=-2540.56813 A=.012
% ifdef ldau
        IDU= 0 0 2  UH= 0 0 0.1 JH= 0 0 0
% endif
% const udiag=t rdvext=0 bxcs=0 alat=5.406
HAM     UDIAG={udiag} NSPIN=2 NONCOL=f QASA=0 SX={sx} RDVEXT={rdvext} BXCSCAL={bxcs}
STRUC   NBAS=1 NSPEC=1 NL=3
        ALAT={alat} PLAT=  -.5 .5 .5  .5 -.5 .5  .5 .5 -.5
#                   SLAT=   -4  4  4   4  -4  4   4  4  -4 
% ifdef file
        FILE=site
SITE    FILE=site
% endif
SITE    ATOM=A POS= 0 0 0
% const nit=1
ITER    UMIX=1 NIT={nit} CONVC=1D-7 CONV=0
MIX     UMIX=1
START   CNTROL=0 BEGMOM=1 NIT=1 CNVG=1D-7

Exchange J0 vs bxc (set bxcs=1)
 bxc   mom    J0
-.45 1.4992  3.764
-.40 1.7086  5.610 
-.35 1.8104  6.789
-.30 1.8686  7.443
-.25 1.9249  7.695 
-.23 1.9482  7.690 
-.20 2.0020  7.862 
-.17 2.0347  8.009 
-.15 2.0710  7.830 
-.13 2.1389  8.813 
-.10 2.2009 10.099
-.08 2.2200 10.593
-.05 2.2391 11.054 
  0  2.2620 10.921
 .05 2.2981 10.038
 .08 2.3413  9.472 
 .10 2.3658  8.723
 .12 2.4296  8.323
 .13 2.4769  9.163
 .14 2.5119 10.435
 .15 2.5384 11.717

Moment as calculated by the band code lm using:
lm fe -vnit=10 -vtwoc=0 -vbxcs=1 -vnk=16  -vtwoc=f -vfile=f --iactiv
 bxc   mom  
-.3   1.9091
-.2   2.0332
-.1   2.1727
 0    2.2633
0.1   2.3783
