#!/bin/tcsh -f
# Extract dj/dz (in mRy) from exchange calculations.
# Can extract from job 10 output file or job 11 output file.

options:
switch ($1)
  case "-job10":
     set job10; shift; goto options

  case "-*":
     echo 'getJ0z : no switch "'$1'"' ... aborting ; exit -1
endsw

if ($#argv == 0) then
  echo "usage: getJz [switches] filename"
  exit -1
endif
if ($#argv != 1) then
  echo missing or extraneous arguments $argv  ... aborting
  exit -1
endif
if (! -f $1) then
  echo file \"$1\" not readable ... aborting
  exit -1
endif
set fn = $1

if ($?job10) then
  cat $fn | awk '/all pairs connected/, /resolved by/' | awk '{if ($1 == "Sum" || $1 == "J_0") {next} else {if ($1 == "site") printf "\n" ; else printf "%s ", $4}}'

else
  cat $fn | awk '/, z=/, /avg/' | awk '{if ($1 == "-------" || $1 == "avg") {next}; if ($1 == "Sum") {printf "\n";printf "%s %s ", $12,$13;getline} else {printf "%s ", $5}}'
endif
echo ' '
