51   0   0   0      0   0   1             Gamma to H
51   0   0   1      0  .5  .5             H to N
51   0  .5  .5     .5  .5  .5             N to P
51  .5  .5  .5      0   0   0             P to Gamma
51   0   0   0     .5  .5   0             Gamma to N
0    0 0 0  0 0 0

... For fermi surface plotting
 vx     range  n     vy     range  n   height  band
1 0 0   -1 1   51   0 1 0   -1 1   51   0.00    4
1 0 0   -1 1   51   0 1 0   -1 1   51   0.00    5

