#!/bin/tcsh -f

  if ($#argv > 0) goto defaults
message:
  echo  ' usage: testex ext'
  exit -1

defaults:
set nk=12
set ext = $1
set cbya
#if ($ext == "co") set nk = 12
if ($ext == "co") set cbya = '-vcbya=1.625'
if ($ext == "fept") set nk = 20

# Look for mcx matrix calculator program
unalias mcx
if `mcx --h |& head -1 | awk '{print ($7 == "(vsn" && ($8 * 1 >= 1.038))}'` set have_mc

if (! -e gf/test/ctrl.$ext) then
  echo testex: missing input file gf/test/ctrl.$ext
  goto message
endif  

if (! -e gf/test/out.$ext.2c.nk=$nk.job11) goto chk2e

echo ' '
echo -------------- testing $ext, 2rd order H ------------
echo "rm a.$ext; cp gf/test/*.$ext .; cp gf/test/a.$ext.2c a.$ext"
echo "rm a.$ext; cp gf/test/{q.bulk,*.$ext} .; cp gf/test/a.$ext.2c a.$ext"
rm a.$ext; cp gf/test/{q.bulk,*.$ext} .; cp gf/test/a.$ext.2c a.$ext
echo "lmstr $ext -vnk=$nk -vbzj=0 -vtwoc=t -vccor=f -vdble=0 $cbya -vexc=10 >out"
lmstr $ext -vnk=$nk -vbzj=0 -vtwoc=t -vccor=f -vdble=0 $cbya -vexc=10 >out
echo "lm    $ext -vnk=$nk -vbzj=0 -vtwoc=t -vccor=f -vdble=0 $cbya -vexc=10  <<END >out"
lm    $ext -vnk=$nk -vbzj=0 -vtwoc=t -vccor=f -vdble=0 $cbya -vexc=10  <<END >out
1

q
END

echo "lmgf  $ext -vnk=$nk -vbzj=0 -vtwoc=t -vccor=f -vdble=0 $cbya -vexc=10 > out.job10"
lmgf  $ext -vnk=$nk -vbzj=0 -vtwoc=t -vccor=f -vdble=0 $cbya -vexc=10 > out.job10
echo "echo i | lmgf  $ext -vnk=$nk -vbzj=0 -vtwoc=t -vccor=f -vdble=0 $cbya -vexc=11 -vtetra=f > out.job11"
echo i | lmgf  $ext -vnk=$nk -vbzj=0 -vtwoc=t -vccor=f -vdble=0 $cbya -vexc=11 -vtetra=f > out.job11

echo "----        doing diff out.job10 gf/test/out.$ext.2c.nk=$nk.job10 ---"
diff -w out.job10 gf/test/out.$ext.2c.nk=$nk.job10 | head -40
echo "----        done  diff out.job10 gf/test/out.$ext.2c.nk=$nk.job10 ---"

echo "----        doing diff out.job11 gf/test/out.$ext.2c.nk=$nk.job11 ---"
diff -w out.job11 gf/test/out.$ext.2c.nk=$nk.job11 | head -20
echo "----        done  diff out.job11 gf/test/out.$ext.2c.nk=$nk.job11 ---"

echo "---- compare jr.$ext to gf/test/jr.$ext.$nk.2c.gz..."
if ($?have_mc) then
  echo "gunzip -c gf/test/jr.$ext.$nk.2c.gz > out"
        gunzip -c gf/test/jr.$ext.$nk.2c.gz > out
  echo "mcx -f2f5.0,1pe12.5 jr.$ext out -- -max:g:"
  mcx -f2f5.0,1pe12.5 jr.$ext out -- -max:g:
else
  echo "gunzip -c gf/test/jr.$ext.$nk.2c.gz | sed 's/\.\([0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]\)[0-9]*/.\1/g' > out.ref"
        gunzip -c gf/test/jr.$ext.$nk.2c.gz | sed 's/\.\([0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]\)[0-9]*/.\1/g' > out.ref
  echo "cat jr.$ext | sed 's/\.\([0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]\)[0-9]*/.\1/g' > out"
        cat jr.$ext | sed 's/\.\([0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]\)[0-9]*/.\1/g' > out
  echo "diff out out.ref | head -20"
  diff out out.ref | head -20
  if (! $status) echo files are the same to 8 decimal places
endif
echo "---- done comparing jr.$ext to gf/test/jr.$ext.$nk.2c.gz ..."

# echo "----        doing zdiff jr.$ext gf/test/jr.$ext.$nk.2c.gz ---"
# zdiff jr.$ext gf/test/jr.$ext.$nk.2c.gz | head -20
# echo "----        done  zdiff jr.$ext gf/test/jr.$ext.$nk.2c.gz ---"

chk2e:

#if (! -e gf/test/out.$ext.3c.nk=$nk.job11) goto chk3e

echo ' '
echo -------------- testing $ext, 3rd order H ------------
echo "rm -f a.$ext; cp gf/test/*.$ext ."
rm a.$ext; cp gf/test/*.$ext .
echo "lmstr $ext -vnk=$nk -vbzj=0 -vtwoc=f -vccor=f -vdble=0 $cbya -vexc=10 >out"
lmstr $ext -vnk=$nk -vbzj=0 -vtwoc=f -vccor=f -vdble=0 $cbya -vexc=10 >out
echo 'lm is needed only to get the fermi level:'
echo "lm    $ext -vnk=$nk -vbzj=0 -vtwoc=f -vccor=f -vdble=0 $cbya -vexc=10  <<END >out"
      lm    $ext -vnk=$nk -vbzj=0 -vtwoc=f -vccor=f -vdble=0 $cbya -vexc=10  <<END >out
1

q
END
echo "lmgf  $ext -vnk=$nk -vbzj=0 -vtwoc=f -vccor=f -vdble=0 $cbya -vexc=10 > out.job10"
lmgf  $ext -vnk=$nk -vbzj=0 -vtwoc=f -vccor=f -vdble=0 $cbya -vexc=10 > out.job10
echo "echo i | lmgf  $ext -vnk=$nk -vbzj=0 -vtwoc=f -vccor=f -vdble=0 $cbya -vexc=11 -vtetra=f > out.job11"
echo i | lmgf  $ext -vnk=$nk -vbzj=0 -vtwoc=f -vccor=f -vdble=0 $cbya -vexc=11 -vtetra=f > out.job11

echo ' '
echo ' done' executing lmgf to make jr.fe.  Compare time to equivalent job in test directory
grep CPU out.job10
grep CPU gf/test/out.$ext.3c.nk=$nk.job10
echo ' '

echo "----        doing diff out.job10 gf/test/out.$ext.3c.nk=$nk.job10 ---"
diff -w out.job10 gf/test/out.$ext.3c.nk=$nk.job10 | head -40
echo "----        done  diff out.job10 gf/test/out.$ext.3c.nk=$nk.job10 ---"

echo "----        doing diff out.job11 gf/test/out.$ext.3c.nk=$nk.job11 ---"
diff -w out.job11 gf/test/out.$ext.3c.nk=$nk.job11 | head -20
echo "----        done  diff out.job11 gf/test/out.$ext.3c.nk=$nk.job11 ---"

echo "---- compare jr.$ext to gf/test/jr.$ext.$nk.gz..."
if ($?have_mc) then
  echo "gunzip -c gf/test/jr.$ext.$nk.gz > out"
        gunzip -c gf/test/jr.$ext.$nk.gz > out
  echo "mcx -f2f5.0,1pe12.5 jr.$ext out -- -max:g:"
  mcx -f2f5.0,1pe12.5 jr.$ext out -- -max:g:
else
  echo "gunzip -c gf/test/jr.$ext.$nk.gz | sed 's/\.\([0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]\)[0-9]*/.\1/g' > out.ref"
        gunzip -c gf/test/jr.$ext.$nk.gz | sed 's/\.\([0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]\)[0-9]*/.\1/g' > out.ref
  echo "cat jr.$ext | sed 's/\.\([0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]\)[0-9]*/.\1/g' > out"
        cat jr.$ext | sed 's/\.\([0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]\)[0-9]*/.\1/g' > out
  echo "diff out out.ref | head -20"
  diff out out.ref | head -20
  if (! $status) echo files are the same to 8 decimal places
endif
echo "---- done comparing jr.$ext to gf/test/jr.$ext.$nk.gz ..."


# echo "----        doing zdiff jr.$ext gf/test/jr.$ext.$nk.gz ---"
# zdiff jr.$ext gf/test/jr.$ext.$nk.gz | head -20
# echo "----        done  zdiff jr.$ext gf/test/jr.$ext.$nk.gz ---"

chk3e:
