#!/bin/tcsh

# A shell script to change numerical exponents into a 'canonical' format
# Unless there is an optional second argument, 
# it copies the original file (argument $1) to $1~
# If there is a second argument, it copies the original to that.

alias standard-exponent 'sed '"'"'s/\([0-9.]\)D\([+-]\)/\1E\2/g'"'" 

# --- Pick off switches ---
while (`echo $1 | sed -e 's/\(.\).*/\1/' `  ==  "-")
  set arg1 = $1; shift
  if ($?verb) echo test.lm: parsing switch $arg1
  switch ($arg1)
    case "--quiet":
      set quiet
      breaksw
    case "--d":
      set dfmt
      alias standard-exponent 'sed '"'"'s/\([0-9.]\)E\([+-]\)/\1D\2/g'"'" 
      breaksw
    default:
      echo unrecognized switch $arg1
      echo 'usage: convert-file-to-standard-exponent [--quiet] [--d] [filename] [saved-filename]'
      exit -1
  endsw

end

if ($#argv == 0) exit
if (! -r $1) exit
if (! -w $1) exit


set tmpfile = $1~
if ($#argv > 1) set tmpfile = $2

if ($?quiet == 0) then
  if ($?dfmt == 0)  echo "convert-file-to-standard-exponent: substituting D exponent to E in file $1 ... original in $tmpfile"
  if ($?dfmt != 0)  echo "convert-file-to-standard-exponent: substituting E exponent to D in file $1 ... original in $tmpfile"

cp $1 $tmpfile
cat $tmpfile | standard-exponent > $1
