rdcmd:  lmfa cs
 ---------------  START LMFA - ref: fa8d2b4 ---------------

 rdctrl: reset global max nl from 4 to 5

 rdctrl: reading basis parameters from file basp
 ioorbp: read species Cs        RSMH,EH RSMH2,EH2 PZ
         reset nkaph from 1 to 3

 LMFA:     nbas = 2  nspec = 1  verb 30
 pot:
 libxc     GGA X (Perdew, Burke & Ernzerhof) + GGA C (Perdew, Burke & Ernzerhof)
 autogen:  mto basis(4), pz(1)   Autoread: pz(1)

                Plat                                  Qlat
   1.000000   0.000000   0.000000        1.000000   0.000000   0.000000
   0.000000   1.000000   0.000000        0.000000   1.000000   0.000000
   0.000000   0.000000   1.000000        0.000000   0.000000   1.000000
   alat = 11.643609  Cell vol = 1578.566284

 LATTC:  as= 2.000   tol=1.00e-16   alat=11.64361   awald= 0.172   lmax=6
         r1=  3.675   nkd= 203      q1=  4.457   nkg= 365

 SGROUP: 1 symmetry operations from 0 generators
 SYMLAT: Bravais system is cubic with 48 symmetry operations.
 SYMCRY: crystal invariant under 48 symmetry operations for tol=1e-5
 GROUPG: the following are sufficient to generate the space group:
         i*r3d r2(0,1,1)
         i*r3d r2(0,1,1)
 MKSYM:  found 48 space group operations ... includes inversion

 SPLCLS:  1 species split into 2 classes

 FREEAT: G tolerance for envelope functions : 1e-16
 Search criteria for local orbitals:  QLOC: qistl > 2e-3  ELOC: eig < -1 Ry

 Species Cs:  Z=55  Qc=48  R=4.939085  Q=0
 mesh:   rmt=4.939085  rmax=49.263484  a=0.01  nr=1261  nr(rmax)=1491
  Pl=  6.5     5.5     5.5     4.5     5.5    
  Ql=  1.0     6.0     0.0     0.0     0.0    

  iter     qint         drho          vh0          rho0          vsum     beta
    1   55.000000   3.255E+04      275.0000    0.2735E+03     -110.5825   0.30
   57   55.000000   3.929E-05      688.0758    0.9649E+06     -370.5180   0.30


 Search for possible local orbitals
 LO l=1: specified by user : PZ=15.9421
 high-lying LO l=2: specified PZ=6.300

 sumev=-6.112445  etot=-15573.829100  eref=0.000000

 Optimise free-atom basis for species Cs, rmt=4.939085
 l  it    Rsm      Eh     stiffR   stiffE      Eval      Exact     Pnu    Ql
 0  50   5.416  -0.199       9.9    150.8   -0.15306  -0.15333    6.77   1.00
 ... rsm exceeded rmt .. repeat with rsm=rmt
 0   4   4.939  -0.135       9.9    580.5   -0.15300  -0.15333    6.77   1.00
 1  50   1.950  -0.870       1.3      2.9   -0.99318  -0.99319    5.94   6.00
 2  17   3.358  -0.100      40.2   -199.4   -0.01826  -0.02829    5.78   0.00
 eigenvalue sum:  exact  -6.11245    opt basis  -6.11211    error 0.00033

 Fit local orbitals to sm hankels, species Cs, rmt=4.939085
 l   Rsm    Eh     Q(r>rmt)   Eval      Exact     Pnu     K.E.   fit K.E.  Gmax
 1  1.685 -0.764   0.00390  -0.99318  -0.99319   5.942  -0.7028  -0.7028    7.4
 ___________________________________________________________________________
 setting up basis
    V(rsm*sqrt(l+1))=-2.000
   V(rsm2*sqrt(l+1))=-0.200
                 ctp      rm     rm2        rsm    rsm2       gmax
  basis l=0:   7.214   2.156   6.394      2.156   6.394      5.631
  basis l=1:  11.760   2.156   6.394      1.524   4.521      8.187
  basis l=2:  14.269   2.156   6.394      1.245   3.691     10.353
  basis l=3:   0.000   2.156   6.394      1.078   3.197     12.361
  basis l=4:   0.000   2.156   6.394      0.964   2.859     14.293
 ___________________________________________________________________________

 Autogenerated Pnu:  0.000 0.000 0.000 0.000 0.000
 Autogenerated PZ:  0.000 15.942 6.300 0.000 0.000


 tailsm: fit tails to 6 smoothed hankels, rmt= 4.93908, rsm= 2.46954
    q(fit):     0.623322    rms diff:   0.000004
    fit: r>rmt  0.623322   r<rmt  1.362959   qtot  1.986281
    rho: r>rmt  0.623322   r<rmt  6.376678   qtot  7.000000

 coretail: q=5.09e-5, rho(rmt)=4.73e-4.  Fit with Hankel e=-7.9129  coeff=271.|

 FREEAT:  writing file basp0

 FREEAT:  estimate HAM_GMAX from RSMH:  GMAX=8.2 (valence)  7.4 (local orbitals)
 Exit 0 LMFA
 CPU time:  0.299s   Wall clock 0.332s  at  21:13:32 28.04.2019  on  nmscde001136.nms.kcl
rdcmd:  lmf  cs -vnk=8
 ---------------  START LMF - ref: fa8d2b4 ----------------

 rdctrl: reset global max nl from 4 to 5

 rdctrl: reading basis parameters from file basp
 ioorbp: read species Cs        RSMH,EH RSMH2,EH2 PZ
         reset nkaph from 1 to 3

 LMF:      nbas = 2  nspec = 1  verb 30
 pot:
 libxc     GGA X (Perdew, Burke & Ernzerhof) + GGA C (Perdew, Burke & Ernzerhof)
 float:    float P LDA-style, spin-av Pz
 autoread: mto basis(4), pz(1)
 bz:       metal(5), tetra, invit 

                Plat                                  Qlat
   1.000000   0.000000   0.000000        1.000000   0.000000   0.000000
   0.000000   1.000000   0.000000        0.000000   1.000000   0.000000
   0.000000   0.000000   1.000000        0.000000   0.000000   1.000000
   alat = 11.643609  Cell vol = 1578.566284

 LATTC:  as= 2.000   tol=1.00e-16   alat=11.64361   awald= 0.172   lmax=6
         r1=  3.675   nkd= 203      q1=  4.457   nkg= 365

 SGROUP: 1 symmetry operations from 0 generators
 SYMLAT: Bravais system is cubic with 48 symmetry operations.
 SYMCRY: crystal invariant under 48 symmetry operations for tol=1e-5
 GROUPG: the following are sufficient to generate the space group:
         i*r3d r2(0,1,1)
         i*r3d r2(0,1,1)
 MKSYM:  found 48 space group operations ... includes inversion

 SPLCLS:  1 species split into 2 classes
 BZMESH: 35 irreducible QP from 512 ( 8 8 8 )  shift= F F F
 TETIRR: sorting 3072 tetrahedra ... 250 inequivalent ones found

 species data:  augmentation                           density
 spec       rmt   rsma lmxa kmxa      lmxl     rg   rsmv  kmxv foca   rfoca
 Cs       4.939  1.976    4    3         4  1.235  2.470     4    1   1.976

 MSHSIZ: mesh has 27 x 27 x 27 divisions; length 0.431, 0.431, 0.431
         generated from gmax = 7.4 a.u. : 10827 vectors of 19683 (55%)

 GVLIST: gmax = 7.4 a.u. created 10827 vectors of 19683 (55%)
         mesh has 27 x 27 x 27 divisions; length 0.431, 0.431, 0.431
 SGVSYM: 325 symmetry stars found for 10827 reciprocal lattice vectors
 

 Makidx:  hamiltonian dimensions Low, Int, High, Negl: 80 0 36 34
 suham :  50 augmentation channels, 50 local potential channels  Maximum lmxa=4

 sugcut:  make orbital-dependent reciprocal vector cutoffs for tol=1.0e-16
 spec      l    rsm    eh     gmax    last term   cutoff
  Cs       0    3.53  -0.50   3.443    1.89E-16    1045 
  Cs       1    2.49  -0.50   4.974    1.54E-16    3239 
  Cs       2    2.04  -0.50   6.252    1.07E-16    6619 
  Cs       3    1.76  -0.50   7.427    1.69E-16   10827*
  Cs       0    7.39  -0.50   1.643    2.94E-16     123 
  Cs       1    5.22  -0.50   2.351    6.75E-16     341 
  Cs       2    4.27  -0.50   2.927    1.74E-16     691 
  Cs       3    3.69  -0.50   3.448    2.20E-16    1045 
 

 lmfp  : no rst file ... try to overlap atomic densities
 rdovfa: read and overlap free-atom densities (mesh density) ...
 rdovfa: expected Cs,      read Cs       with rmt=  4.9391  mesh  1261  0.010

 Free atom and overlapped crystal site charges  spec 1  site 1:
   ib    true(FA)    smooth(FA)  true(OV)    smooth(OV)    local
    1    6.376678    1.363034    6.610505    1.596861    5.013644

 Free atom and overlapped crystal site charges  spec 1  site 2:
   ib    true(FA)    smooth(FA)  true(OV)    smooth(OV)    local
    2    6.376678    1.363034    6.610505    1.596861    5.013644

 Smooth charge on mesh:            3.972718
 Sum of local charges:            10.027289
 Total valence charge:            14.000007
 Sum of core charges:             96.000000
 Sum of nuclear charges:        -110.000000
 Homogeneous background:           0.000000
 Deviation from neutrality:        0.000007

 --- BNDFP:  begin iteration 1 of 80 ---

 Average es pot at rmt = 0.113765  avg sphere pot = 0.253210   vconst = -0.113765
 smooth rhoves      1.926407   charge     3.972718
 smooth rhoeps =   -1.157874   rhomu =   -1.158383  avg vxc =   -0.325058 

 elocp:

 Fit local orbitals to sm hankels, species Cs, rmt=4.939085
  l  type    Pnu      Eval        K.E.       Rsm       Eh      Q(r>rmt)    Fit K.E.
  1  low    5.942   -0.993180   -0.702796   1.69153  -0.76706   0.00735   -0.702796 

 locpot:

 site  1  z= 55.0  rmt= 4.93908  nr=1261  a=0.010  nlml=25  rg=1.235  Vfloat=T
 sm core charge = 0.037439 (sphere) + 0.000473 (spillout) = 0.037912
 potential shift to crystal energy zero:    0.000020

 site  2  z= 55.0  rmt= 4.93908  nr=1261  a=0.010  nlml=25  rg=1.235  Vfloat=T
 sm core charge = 0.037439 (sphere) + 0.000473 (spillout) = 0.037912
 potential shift to crystal energy zero:    0.000020

 Energy terms:             smooth           local            total
   rhoval*vef             -2.664194      -109.039791      -111.703985
   rhoval*ves            -13.821473       -82.420975       -96.242449
   psnuc*ves              17.674288   -126910.741368   -126893.067080
   utot                    1.926407    -63496.581172    -63494.654765
   rho*exc                -1.157874      -769.121549      -770.279424
   rho*vxc                -1.158383     -1004.242444     -1005.400826
   valence chg             3.972718        10.027289        14.000007
   core charge            96.000000         0.000000        96.000000

 Charges:  valence    14.00001   cores    96.00000   nucleii  -110.00000
    hom background     0.00000   deviation from neutrality:      0.00001

 sugcut:  make orbital-dependent cutoffs for local orbitals, tol=1.0e-16
 spec      l    rsm    eh     gmax    last term   cutoff
  Cs       1    1.69  -0.77   7.369    1.10E-16   10779 
 

 Start first of two band passes ...
 bndfp:  kpt 1 of 35, k=  0.00000  0.00000  0.00000
 -0.9079 -0.9079 -0.9079 -0.9010 -0.9010 -0.9010 -0.2488 -0.0776 -0.0775
 bndfp:  kpt 11 of 35, k=  0.37500  0.25000  0.00000
 -0.9095 -0.9077 -0.9052 -0.9034 -0.9032 -0.9013 -0.1761 -0.1096 -0.0581
 bndfp:  kpt 21 of 35, k=  0.37500  0.25000  0.12500
 -0.9093 -0.9079 -0.9059 -0.9034 -0.9028 -0.9015 -0.1707 -0.1045 -0.0569
 bndfp:  kpt 31 of 35, k=  0.50000  0.50000  0.25000
 -0.9092 -0.9092 -0.9050 -0.9050 -0.9024 -0.9024 -0.0975 -0.0975 -0.0624

 BZWTS : --- Tetrahedron Integration ---
 BZINTS: Fermi energy:     -0.125648;  14.000000 electrons;  D(Ef):   42.255
         Sum occ. bands:  -11.1995836  incl. Bloechl correction:   -0.003543

 Saved qp weights ...
 Start second band pass ...
 bndfp:  kpt 1 of 35, k=  0.00000  0.00000  0.00000
 -0.9079 -0.9079 -0.9079 -0.9010 -0.9010 -0.9010 -0.2488 -0.0776 -0.0775
 bndfp:  kpt 11 of 35, k=  0.37500  0.25000  0.00000
 -0.9095 -0.9077 -0.9052 -0.9034 -0.9032 -0.9013 -0.1761 -0.1096 -0.0581
 bndfp:  kpt 21 of 35, k=  0.37500  0.25000  0.12500
 -0.9093 -0.9079 -0.9059 -0.9034 -0.9028 -0.9015 -0.1707 -0.1045 -0.0569
 bndfp:  kpt 31 of 35, k=  0.50000  0.50000  0.25000
 -0.9092 -0.9092 -0.9050 -0.9050 -0.9024 -0.9024 -0.0975 -0.0975 -0.0624

 BZWTS : --- Tetrahedron Integration ---
 BZINTS: Fermi energy:     -0.125648;  14.000000 electrons;  D(Ef):   42.255
         Sum occ. bands:  -11.1995836  incl. Bloechl correction:   -0.003543

 Saved qp weights ...

 mkrout:  Qtrue      sm,loc       local
   1    6.561331    3.970070    2.591261
   2    6.560940    3.969504    2.591436

 Symmetrize density..

 Make new boundary conditions for phi,phidot..

 site    1   species   1:Cs      
 l  idmod     ql         ebar        pold        ptry        pfree        pnew
 0     0    0.400203   -0.176032    6.710000    6.627087    6.500000    6.627087
 1     0    0.119261   -0.168622    6.500000    6.244065    6.250000    6.500000
 1     0    sc         -0.904648    5.942100    5.946509    5.250000   15.946509
 2     0    0.068320   -0.157410    5.310000    5.293314    5.147584    5.293314
 2     0    sc          0.000000    6.300000    6.147584    6.147584    6.300000
 3     0    0.001766   -0.417371    4.130000    4.095973    4.102416    4.121119
 4     0    0.000335   -0.771727    5.088586    5.063428    5.077979    5.088586

 site    2   species   1:Cs      
 l  idmod     ql         ebar        pold        ptry        pfree        pnew
 0     0    0.399622   -0.176056    6.710000    6.627040    6.500000    6.627040
 1     0    0.119526   -0.168602    6.500000    6.244080    6.250000    6.500000
 1     0    sc         -0.904648    5.942100    5.946509    5.250000   15.946509
 2     0    0.068242   -0.157408    5.310000    5.293317    5.147584    5.293317
 2     0    sc          0.000000    6.300000    6.147584    6.147584    6.300000
 3     0    0.001767   -0.417175    4.130000    4.095988    4.102416    4.121119
 4     0    0.000335   -0.771935    5.088586    5.063423    5.077979    5.088586

 Harris energy:
 sumev=      -11.199584  val*vef=    -111.703985   sumtv=     100.504402
 sumec=        0.000000  cor*vef=       0.000000   ttcor=   33016.648880
 rhoeps=    -770.279424     utot=  -63494.654765    ehar=  -31147.780906

 srhov:     -8.069189   -103.266347   -111.335536 sumev=  -11.199584   sumtv=  100.135952

 Kohn-Sham energy:
 sumtv=      100.135952  sumtc=     33016.648880   ekin=    33116.784833
 rhoep=     -770.229308   utot=    -63494.336499   ehks=   -31147.780975
  
 mixing: mode=B  nmix=4  beta=1  elind=.112
 mixrho:  sought 4 iter from file mixm; read 0.  RMS DQ=3.50e-2
 AMIX: nmix=0 mmix=8  nelts=16772  beta=1  tm=5  rmsdel=3.5e-2
 unscreened rms difference:  smooth  0.007872   local  0.019302
   screened rms difference:  smooth  0.007894   local  0.019302   tot  0.034964

 iors  : write restart file (binary, mesh density)

   it  1  of 80    ehf=  -31147.780906   ehk=  -31147.780975
h nk=8 ehf=-31147.7809064 ehk=-31147.7809747

 --- BNDFP:  begin iteration 2 of 80 ---

 Average es pot at rmt = 0.156328  avg sphere pot = 0.213480   vconst = -0.156328
 smooth rhoves      6.112262   charge     8.817303
 smooth rhoeps =   -4.000165   rhomu =   -4.001629  avg vxc =   -0.361158 

 elocp:

 Fit local orbitals to sm hankels, species Cs, rmt=4.939085
  l  type    Pnu      Eval        K.E.       Rsm       Eh      Q(r>rmt)    Fit K.E.
  1  low    5.947   -0.903988   -0.615063   2.31835  -2.17542   0.01426   -0.615063 

 locpot:

 site  1  z= 55.0  rmt= 4.93908  nr=1261  a=0.010  nlml=25  rg=1.235  Vfloat=T
 sm core charge = 0.037439 (sphere) + 0.000473 (spillout) = 0.037912
 potential shift to crystal energy zero:    0.000004

 site  2  z= 55.0  rmt= 4.93908  nr=1261  a=0.010  nlml=25  rg=1.235  Vfloat=T
 sm core charge = 0.037439 (sphere) + 0.000473 (spillout) = 0.037912
 potential shift to crystal energy zero:    0.000004

 Energy terms:             smooth           local            total
   rhoval*vef            -11.652440       -99.895978      -111.548418
   rhoval*ves            -17.499598       -78.631408       -96.131007
   psnuc*ves              29.724122   -126922.354933   -126892.630811
   utot                    6.112262    -63500.493171    -63494.380909
   rho*exc                -4.000165      -766.240241      -770.240406
   rho*vxc                -4.001629     -1000.520103     -1004.521733
   valence chg             8.817303         5.182697        14.000000
   core charge            96.000000         0.000000        96.000000

 Charges:  valence    14.00000   cores    96.00000   nucleii  -110.00000
    hom background     0.00000   deviation from neutrality:      0.00000

 sugcut:  make orbital-dependent cutoffs for local orbitals, tol=1.0e-16
 spec      l    rsm    eh     gmax    last term   cutoff
  Cs       1    2.32  -2.18   5.354    1.19E-16    4067 
 

 Start first of two band passes ...
 bndfp:  kpt 1 of 35, k=  0.00000  0.00000  0.00000
 -0.9200 -0.9200 -0.9200 -0.9133 -0.9133 -0.9133 -0.2542 -0.0836 -0.0836
 bndfp:  kpt 11 of 35, k=  0.37500  0.25000  0.00000
 -0.9216 -0.9198 -0.9174 -0.9156 -0.9154 -0.9135 -0.1817 -0.1153 -0.0643
 bndfp:  kpt 21 of 35, k=  0.37500  0.25000  0.12500
 -0.9214 -0.9200 -0.9180 -0.9156 -0.9150 -0.9137 -0.1763 -0.1102 -0.0631
 bndfp:  kpt 31 of 35, k=  0.50000  0.50000  0.25000
 -0.9213 -0.9213 -0.9172 -0.9172 -0.9146 -0.9146 -0.1031 -0.1031 -0.0688

 BZWTS : --- Tetrahedron Integration ---
 BZINTS: Fermi energy:     -0.131313;  14.000000 electrons;  D(Ef):   42.167
         Sum occ. bands:  -11.3570292  incl. Bloechl correction:   -0.003537

 Saved qp weights ...
 Start second band pass ...
 bndfp:  kpt 1 of 35, k=  0.00000  0.00000  0.00000
 -0.9200 -0.9200 -0.9200 -0.9133 -0.9133 -0.9133 -0.2542 -0.0836 -0.0836
 bndfp:  kpt 11 of 35, k=  0.37500  0.25000  0.00000
 -0.9216 -0.9198 -0.9174 -0.9156 -0.9154 -0.9135 -0.1817 -0.1153 -0.0643
 bndfp:  kpt 21 of 35, k=  0.37500  0.25000  0.12500
 -0.9214 -0.9200 -0.9180 -0.9156 -0.9150 -0.9137 -0.1763 -0.1102 -0.0631
 bndfp:  kpt 31 of 35, k=  0.50000  0.50000  0.25000
 -0.9213 -0.9213 -0.9172 -0.9172 -0.9146 -0.9146 -0.1031 -0.1031 -0.0688

 BZWTS : --- Tetrahedron Integration ---
 BZINTS: Fermi energy:     -0.131313;  14.000000 electrons;  D(Ef):   42.167
         Sum occ. bands:  -11.3570292  incl. Bloechl correction:   -0.003537

 Saved qp weights ...

 mkrout:  Qtrue      sm,loc       local
   1    6.548837    1.824759    4.724078
   2    6.571061    1.861470    4.709590

 Symmetrize density..

 Make new boundary conditions for phi,phidot..

 site    1   species   1:Cs      
 l  idmod     ql         ebar        pold        ptry        pfree        pnew
 0     0    0.379929   -0.183989    6.627087    6.619899    6.500000    6.619899
 1     0    0.122273   -0.174089    6.500000    6.244668    6.250000    6.500000
 1     0    sc         -0.916197    5.946509    5.946775    5.250000   15.946775
 2     0    0.072603   -0.161037    5.293314    5.295366    5.147584    5.295366
 2     0    sc          0.000000    6.300000    6.147584    6.147584    6.300000
 3     0    0.001667   -0.428982    4.121119    4.095507    4.102416    4.121119
 4     0    0.000302   -0.789076    5.088586    5.063163    5.077979    5.088586

 site    2   species   1:Cs      
 l  idmod     ql         ebar        pold        ptry        pfree        pnew
 0     0    0.415626   -0.179551    6.627040    6.628742    6.500000    6.628742
 1     0    0.117881   -0.175833    6.500000    6.243420    6.250000    6.500000
 1     0    sc         -0.916225    5.946509    5.946775    5.250000   15.946775
 2     0    0.063290   -0.164943    5.293317    5.290133    5.147584    5.290133
 2     0    sc          0.000000    6.300000    6.147584    6.147584    6.300000
 3     0    0.001792   -0.408467    4.121119    4.097095    4.102416    4.121119
 4     0    0.000316   -0.760918    5.088586    5.063849    5.077979    5.088586

 Harris energy:
 sumev=      -11.357029  val*vef=    -111.548418   sumtv=     100.191388
 sumec=        0.000000  cor*vef=       0.000000   ttcor=   33016.648880
 rhoeps=    -770.240406     utot=  -63494.380909    ehar=  -31147.781046

 srhov:     -3.899722   -108.078641   -111.978363 sumev=  -11.357029   sumtv=  100.621334

 Kohn-Sham energy:
 sumtv=      100.621334  sumtc=     33016.648880   ekin=    33117.270214
 rhoep=     -770.266135   utot=    -63494.785210   ehks=   -31147.781132
  
 mixing: mode=B  nmix=4  beta=1  elind=.112
 mixrho:  sought 4 iter from file mixm; read 1.  RMS DQ=3.25e-2  last it=3.50e-2
 AMIX: nmix=1 mmix=8  nelts=16772  beta=1  tm=5  rmsdel=3.25e-2
   tj: 0.48148
 unscreened rms difference:  smooth  0.007507   local  0.017337
   screened rms difference:  smooth  0.007508   local  0.017337   tot  0.032474

 iors  : write restart file (binary, mesh density)

   it  2  of 80    ehf=  -31147.781046   ehk=  -31147.781132
 From last iter    ehf=  -31147.780906   ehk=  -31147.780975
 diffe(q)= -0.000139 (0.032474)    tol= 0.000010 (0.000100)   more=T
i nk=8 ehf=-31147.7810456 ehk=-31147.7811316

 --- BNDFP:  begin iteration 3 of 80 ---

 Average es pot at rmt = 0.141778  avg sphere pot = 0.228054   vconst = -0.141778
 smooth rhoves      4.130440   charge     6.613082
 smooth rhoeps =   -2.540145   rhomu =   -2.540777  avg vxc =   -0.349802 

 elocp:

 Fit local orbitals to sm hankels, species Cs, rmt=4.939085
  l  type    Pnu      Eval        K.E.       Rsm       Eh      Q(r>rmt)    Fit K.E.
  1  low    5.947   -0.916171   -0.621593   2.32627  -2.27834   0.01405   -0.621593 

 locpot:

 site  1  z= 55.0  rmt= 4.93908  nr=1261  a=0.010  nlml=25  rg=1.235  Vfloat=T
 sm core charge = 0.037439 (sphere) + 0.000473 (spillout) = 0.037912
 potential shift to crystal energy zero:   -0.000001

 site  2  z= 55.0  rmt= 4.93908  nr=1261  a=0.010  nlml=25  rg=1.235  Vfloat=T
 sm core charge = 0.037439 (sphere) + 0.000473 (spillout) = 0.037912
 potential shift to crystal energy zero:   -0.000001

 Energy terms:             smooth           local            total
   rhoval*vef             -6.842026      -104.915321      -111.757347
   rhoval*ves            -16.769113       -79.557937       -96.327050
   psnuc*ves              25.029993   -126917.879016   -126892.849023
   utot                    4.130440    -63498.718476    -63494.588036
   rho*exc                -2.540145      -767.713161      -770.253306
   rho*vxc                -2.540777     -1002.424336     -1004.965113
   valence chg             6.613082         7.386918        14.000000
   core charge            96.000000         0.000000        96.000000

 Charges:  valence    14.00000   cores    96.00000   nucleii  -110.00000
    hom background     0.00000   deviation from neutrality:      0.00000

 sugcut:  make orbital-dependent cutoffs for local orbitals, tol=1.0e-16
 spec      l    rsm    eh     gmax    last term   cutoff
  Cs       1    2.33  -2.28   5.336    1.35E-16    3959 
 

 Start first of two band passes ...
 bndfp:  kpt 1 of 35, k=  0.00000  0.00000  0.00000
 -0.9191 -0.9191 -0.9191 -0.9123 -0.9123 -0.9123 -0.2545 -0.0838 -0.0838
 bndfp:  kpt 11 of 35, k=  0.37500  0.25000  0.00000
 -0.9207 -0.9189 -0.9166 -0.9145 -0.9144 -0.9126 -0.1820 -0.1156 -0.0645
 bndfp:  kpt 21 of 35, k=  0.37500  0.25000  0.12500
 -0.9205 -0.9191 -0.9172 -0.9146 -0.9140 -0.9127 -0.1766 -0.1105 -0.0633
 bndfp:  kpt 31 of 35, k=  0.50000  0.50000  0.25000
 -0.9204 -0.9204 -0.9167 -0.9158 -0.9136 -0.9136 -0.1033 -0.1032 -0.0691

 BZWTS : --- Tetrahedron Integration ---
 BZINTS: Fermi energy:     -0.131537;  14.000000 electrons;  D(Ef):   42.106
         Sum occ. bands:  -11.3460332  incl. Bloechl correction:   -0.003539

 Saved qp weights ...
 Start second band pass ...
 bndfp:  kpt 1 of 35, k=  0.00000  0.00000  0.00000
 -0.9191 -0.9191 -0.9191 -0.9123 -0.9123 -0.9123 -0.2545 -0.0838 -0.0838
 bndfp:  kpt 11 of 35, k=  0.37500  0.25000  0.00000
 -0.9207 -0.9189 -0.9166 -0.9145 -0.9144 -0.9126 -0.1820 -0.1156 -0.0645
 bndfp:  kpt 21 of 35, k=  0.37500  0.25000  0.12500
 -0.9205 -0.9191 -0.9172 -0.9146 -0.9140 -0.9127 -0.1766 -0.1105 -0.0633
 bndfp:  kpt 31 of 35, k=  0.50000  0.50000  0.25000
 -0.9204 -0.9204 -0.9167 -0.9158 -0.9136 -0.9136 -0.1033 -0.1032 -0.0691

 BZWTS : --- Tetrahedron Integration ---
 BZINTS: Fermi energy:     -0.131537;  14.000000 electrons;  D(Ef):   42.106
         Sum occ. bands:  -11.3460332  incl. Bloechl correction:   -0.003539

 Saved qp weights ...

 mkrout:  Qtrue      sm,loc       local
   1    6.548171    1.825268    4.722903
   2    6.570469    1.861934    4.708535

 Symmetrize density..

 Make new boundary conditions for phi,phidot..

 site    1   species   1:Cs      
 l  idmod     ql         ebar        pold        ptry        pfree        pnew
 0     0    0.379079   -0.184286    6.619899    6.619270    6.500000    6.619270
 1     0    0.122679   -0.174419    6.500000    6.244470    6.250000    6.500000
 1     0    sc         -0.915662    5.946775    5.946764    5.250000   15.946764
 2     0    0.072452   -0.161329    5.295366    5.295108    5.147584    5.295108
 2     0    sc          0.000000    6.300000    6.147584    6.147584    6.300000
 3     0    0.001671   -0.429643    4.121119    4.095488    4.102416    4.121119
 4     0    0.000303   -0.789182    5.088586    5.063173    5.077979    5.088586

 site    2   species   1:Cs      
 l  idmod     ql         ebar        pold        ptry        pfree        pnew
 0     0    0.415397   -0.179791    6.628742    6.628015    6.500000    6.628015
 1     0    0.117790   -0.176215    6.500000    6.243171    6.250000    6.500000
 1     0    sc         -0.914738    5.946775    5.946744    5.250000   15.946744
 2     0    0.063188   -0.165257    5.290133    5.289611    5.147584    5.289611
 2     0    sc          0.000000    6.300000    6.147584    6.147584    6.300000
 3     0    0.001794   -0.408852    4.121119    4.097111    4.102416    4.121119
 4     0    0.000317   -0.760983    5.088586    5.063867    5.077979    5.088586

 Harris energy:
 sumev=      -11.346033  val*vef=    -111.757347   sumtv=     100.411314
 sumec=        0.000000  cor*vef=       0.000000   ttcor=   33016.648880
 rhoeps=    -770.253306     utot=  -63494.588036    ehar=  -31147.781148

 srhov:     -3.571627   -108.324144   -111.895771 sumev=  -11.346033   sumtv=  100.549738

 Kohn-Sham energy:
 sumtv=      100.549738  sumtc=     33016.648880   ekin=    33117.198618
 rhoep=     -770.261153   utot=    -63494.718612   ehks=   -31147.781147
  
 mixing: mode=B  nmix=4  beta=1  elind=.112
 mixrho:  sought 4 iter from file mixm; read 2.  RMS DQ=1.56e-2  last it=3.25e-2
 broyj:  ir=2  dxmax=0.17  gmax=0.17  wc=1
 unscreened rms difference:  smooth  0.003616   local  0.008343
   screened rms difference:  smooth  0.003616   local  0.008343   tot  0.015627

 iors  : write restart file (binary, mesh density)

   it  3  of 80    ehf=  -31147.781148   ehk=  -31147.781147
 From last iter    ehf=  -31147.781046   ehk=  -31147.781132
 diffe(q)= -0.000102 (0.015627)    tol= 0.000010 (0.000100)   more=T
i nk=8 ehf=-31147.7811479 ehk=-31147.7811472

 --- BNDFP:  begin iteration 4 of 80 ---

 Average es pot at rmt = 0.128442  avg sphere pot = 0.241564   vconst = -0.128442
 smooth rhoves      2.682935   charge     4.570630
 smooth rhoeps =   -1.398217   rhomu =   -1.398347  avg vxc =   -0.335395 

 elocp:

 Fit local orbitals to sm hankels, species Cs, rmt=4.939085
  l  type    Pnu      Eval        K.E.       Rsm       Eh      Q(r>rmt)    Fit K.E.
  1  low    5.947   -0.915203   -0.620075   2.32830  -2.28847   0.01410   -0.620075 

 locpot:

 site  1  z= 55.0  rmt= 4.93908  nr=1261  a=0.010  nlml=25  rg=1.235  Vfloat=T
 sm core charge = 0.037439 (sphere) + 0.000473 (spillout) = 0.037912
 potential shift to crystal energy zero:    0.000010

 site  2  z= 55.0  rmt= 4.93908  nr=1261  a=0.010  nlml=25  rg=1.235  Vfloat=T
 sm core charge = 0.037439 (sphere) + 0.000473 (spillout) = 0.037912
 potential shift to crystal energy zero:    0.000010

 Energy terms:             smooth           local            total
   rhoval*vef             -3.205853      -108.631445      -111.837298
   rhoval*ves            -15.332415       -81.070561       -96.402976
   psnuc*ves              20.698285   -126913.616218   -126892.917933
   utot                    2.682935    -63497.343390    -63494.660455
   rho*exc                -1.398217      -768.859133      -770.257350
   rho*vxc                -1.398347     -1003.903367     -1005.301714
   valence chg             4.570630         9.429370        14.000000
   core charge            96.000000         0.000000        96.000000

 Charges:  valence    14.00000   cores    96.00000   nucleii  -110.00000
    hom background     0.00000   deviation from neutrality:      0.00000

 sugcut:  make orbital-dependent cutoffs for local orbitals, tol=1.0e-16
 spec      l    rsm    eh     gmax    last term   cutoff
  Cs       1    2.33  -2.29   5.331    1.26E-16    3959 
 

 Start first of two band passes ...
 bndfp:  kpt 1 of 35, k=  0.00000  0.00000  0.00000
 -0.9196 -0.9196 -0.9196 -0.9122 -0.9122 -0.9122 -0.2550 -0.0843 -0.0843
 bndfp:  kpt 11 of 35, k=  0.37500  0.25000  0.00000
 -0.9211 -0.9195 -0.9174 -0.9143 -0.9141 -0.9126 -0.1824 -0.1160 -0.0650
 bndfp:  kpt 21 of 35, k=  0.37500  0.25000  0.12500
 -0.9209 -0.9196 -0.9179 -0.9143 -0.9139 -0.9127 -0.1770 -0.1109 -0.0638
 bndfp:  kpt 31 of 35, k=  0.50000  0.50000  0.25000
 -0.9209 -0.9209 -0.9178 -0.9150 -0.9136 -0.9136 -0.1037 -0.1036 -0.0696

 BZWTS : --- Tetrahedron Integration ---
 BZINTS: Fermi energy:     -0.131971;  14.000000 electrons;  D(Ef):   42.108
         Sum occ. bands:  -11.3495297  incl. Bloechl correction:   -0.003539

 Saved qp weights ...
 Start second band pass ...
 bndfp:  kpt 1 of 35, k=  0.00000  0.00000  0.00000
 -0.9196 -0.9196 -0.9196 -0.9122 -0.9122 -0.9122 -0.2550 -0.0843 -0.0843
 bndfp:  kpt 11 of 35, k=  0.37500  0.25000  0.00000
 -0.9211 -0.9195 -0.9174 -0.9143 -0.9141 -0.9126 -0.1824 -0.1160 -0.0650
 bndfp:  kpt 21 of 35, k=  0.37500  0.25000  0.12500
 -0.9209 -0.9196 -0.9179 -0.9143 -0.9139 -0.9127 -0.1770 -0.1109 -0.0638
 bndfp:  kpt 31 of 35, k=  0.50000  0.50000  0.25000
 -0.9209 -0.9209 -0.9178 -0.9150 -0.9136 -0.9136 -0.1037 -0.1036 -0.0696

 BZWTS : --- Tetrahedron Integration ---
 BZINTS: Fermi energy:     -0.131971;  14.000000 electrons;  D(Ef):   42.108
         Sum occ. bands:  -11.3495297  incl. Bloechl correction:   -0.003539

 Saved qp weights ...

 mkrout:  Qtrue      sm,loc       local
   1    6.569081    1.857385    4.711696
   2    6.548812    1.822446    4.726365

 Symmetrize density..

 Make new boundary conditions for phi,phidot..

 site    1   species   1:Cs      
 l  idmod     ql         ebar        pold        ptry        pfree        pnew
 0     0    0.412386   -0.180597    6.619270    6.627408    6.500000    6.627408
 1     0    0.118298   -0.176469    6.500000    6.243392    6.250000    6.500000
 1     0    sc         -0.916833    5.946764    5.946789    5.250000   15.946789
 2     0    0.064131   -0.165446    5.295108    5.290344    5.147584    5.290344
 2     0    sc          0.000000    6.300000    6.147584    6.147584    6.300000
 3     0    0.001794   -0.410039    4.121119    4.097048    4.102416    4.121119
 4     0    0.000320   -0.766762    5.088586    5.063735    5.077979    5.088586

 site    2   species   1:Cs      
 l  idmod     ql         ebar        pold        ptry        pfree        pnew
 0     0    0.381376   -0.184336    6.628015    6.618944    6.500000    6.618944
 1     0    0.122415   -0.175017    6.500000    6.244215    6.250000    6.500000
 1     0    sc         -0.914020    5.946744    5.946729    5.250000   15.946729
 2     0    0.071240   -0.162026    5.289611    5.293927    5.147584    5.293927
 2     0    sc          0.000000    6.300000    6.147584    6.147584    6.300000
 3     0    0.001670   -0.429546    4.121119    4.095558    4.102416    4.121119
 4     0    0.000299   -0.784269    5.088586    5.063318    5.077979    5.088586

 Harris energy:
 sumev=      -11.349530  val*vef=    -111.837298   sumtv=     100.487768
 sumec=        0.000000  cor*vef=       0.000000   ttcor=   33016.648880
 rhoeps=    -770.257350     utot=  -63494.660455    ehar=  -31147.781156

 srhov:     -3.196951   -108.690735   -111.887686 sumev=  -11.349530   sumtv=  100.538156

 Kohn-Sham energy:
 sumtv=      100.538156  sumtc=     33016.648880   ekin=    33117.187037
 rhoep=     -770.260568   utot=    -63494.707614   ehks=   -31147.781145
  
 mixing: mode=B  nmix=4  beta=1  elind=.112
 mixrho:  sought 4 iter from file mixm; read 3.  RMS DQ=2.07e-4  last it=1.56e-2
 broyj:  ir=3  dxmax=0.0017  gmax=3e-3  wc=1
 unscreened rms difference:  smooth  0.000064   local  0.000150
   screened rms difference:  smooth  0.000049   local  0.000150   tot  0.000207

 iors  : write restart file (binary, mesh density)

   it  4  of 80    ehf=  -31147.781156   ehk=  -31147.781145
 From last iter    ehf=  -31147.781148   ehk=  -31147.781147
 diffe(q)= -0.000008 (0.000207)    tol= 0.000010 (0.000100)   more=T
i nk=8 ehf=-31147.7811558 ehk=-31147.7811452

 --- BNDFP:  begin iteration 5 of 80 ---

 Average es pot at rmt = 0.128387  avg sphere pot = 0.241602   vconst = -0.128387
 smooth rhoves      2.678446   charge     4.565626
 smooth rhoeps =   -1.395848   rhomu =   -1.395980  avg vxc =   -0.335352 

 elocp:

 Fit local orbitals to sm hankels, species Cs, rmt=4.939085
  l  type    Pnu      Eval        K.E.       Rsm       Eh      Q(r>rmt)    Fit K.E.
  1  low    5.947   -0.915426   -0.619644   2.32992  -2.30083   0.01411   -0.619644 

 locpot:

 site  1  z= 55.0  rmt= 4.93908  nr=1261  a=0.010  nlml=25  rg=1.235  Vfloat=T
 sm core charge = 0.037439 (sphere) + 0.000473 (spillout) = 0.037912
 potential shift to crystal energy zero:    0.000008

 site  2  z= 55.0  rmt= 4.93908  nr=1261  a=0.010  nlml=25  rg=1.235  Vfloat=T
 sm core charge = 0.037439 (sphere) + 0.000473 (spillout) = 0.037912
 potential shift to crystal energy zero:    0.000009

 Energy terms:             smooth           local            total
   rhoval*vef             -3.199252      -108.663946      -111.863199
   rhoval*ves            -15.325735       -81.101418       -96.427153
   psnuc*ves              20.682627   -126913.629388   -126892.946760
   utot                    2.678446    -63497.365403    -63494.686957
   rho*exc                -1.395848      -768.863209      -770.259057
   rho*vxc                -1.395980     -1003.908689     -1005.304669
   valence chg             4.565626         9.434374        14.000000
   core charge            96.000000         0.000000        96.000000

 Charges:  valence    14.00000   cores    96.00000   nucleii  -110.00000
    hom background     0.00000   deviation from neutrality:      0.00000

 sugcut:  make orbital-dependent cutoffs for local orbitals, tol=1.0e-16
 spec      l    rsm    eh     gmax    last term   cutoff
  Cs       1    2.33  -2.30   5.327    1.20E-16    3959 
 

 Start first of two band passes ...
 bndfp:  kpt 1 of 35, k=  0.00000  0.00000  0.00000
 -0.9192 -0.9192 -0.9192 -0.9123 -0.9123 -0.9123 -0.2549 -0.0843 -0.0843
 bndfp:  kpt 11 of 35, k=  0.37500  0.25000  0.00000
 -0.9207 -0.9190 -0.9167 -0.9145 -0.9144 -0.9126 -0.1824 -0.1160 -0.0650
 bndfp:  kpt 21 of 35, k=  0.37500  0.25000  0.12500
 -0.9205 -0.9191 -0.9172 -0.9146 -0.9140 -0.9127 -0.1770 -0.1109 -0.0638
 bndfp:  kpt 31 of 35, k=  0.50000  0.50000  0.25000
 -0.9204 -0.9204 -0.9168 -0.9157 -0.9136 -0.9136 -0.1037 -0.1036 -0.0696

 BZWTS : --- Tetrahedron Integration ---
 BZINTS: Fermi energy:     -0.131957;  14.000000 electrons;  D(Ef):   42.060
         Sum occ. bands:  -11.3472346  incl. Bloechl correction:   -0.003536

 Saved qp weights ...
 Start second band pass ...
 bndfp:  kpt 1 of 35, k=  0.00000  0.00000  0.00000
 -0.9192 -0.9192 -0.9192 -0.9123 -0.9123 -0.9123 -0.2549 -0.0843 -0.0843
 bndfp:  kpt 11 of 35, k=  0.37500  0.25000  0.00000
 -0.9207 -0.9190 -0.9167 -0.9145 -0.9144 -0.9126 -0.1824 -0.1160 -0.0650
 bndfp:  kpt 21 of 35, k=  0.37500  0.25000  0.12500
 -0.9205 -0.9191 -0.9172 -0.9146 -0.9140 -0.9127 -0.1770 -0.1109 -0.0638
 bndfp:  kpt 31 of 35, k=  0.50000  0.50000  0.25000
 -0.9204 -0.9204 -0.9168 -0.9157 -0.9136 -0.9136 -0.1037 -0.1036 -0.0696

 BZWTS : --- Tetrahedron Integration ---
 BZINTS: Fermi energy:     -0.131957;  14.000000 electrons;  D(Ef):   42.060
         Sum occ. bands:  -11.3472346  incl. Bloechl correction:   -0.003536

 Saved qp weights ...

 mkrout:  Qtrue      sm,loc       local
   1    6.570498    1.868772    4.701726
   2    6.547259    1.808233    4.739025

 Symmetrize density..

 Make new boundary conditions for phi,phidot..

 site    1   species   1:Cs      
 l  idmod     ql         ebar        pold        ptry        pfree        pnew
 0     0    0.414917   -0.180264    6.627408    6.627854    6.500000    6.627854
 1     0    0.118201   -0.176546    6.500000    6.243321    6.250000    6.500000
 1     0    sc         -0.915801    5.946789    5.946767    5.250000   15.946767
 2     0    0.063105   -0.165798    5.290344    5.289644    5.147584    5.289644
 2     0    sc          0.000000    6.300000    6.147584    6.147584    6.300000
 3     0    0.001796   -0.409037    4.121119    4.097144    4.102416    4.121119
 4     0    0.000331   -0.767679    5.088586    5.063720    5.077979    5.088586

 site    2   species   1:Cs      
 l  idmod     ql         ebar        pold        ptry        pfree        pnew
 0     0    0.378731   -0.184714    6.618944    6.618261    6.500000    6.618261
 1     0    0.122525   -0.174947    6.500000    6.244230    6.250000    6.500000
 1     0    sc         -0.914663    5.946729    5.946742    5.250000   15.946742
 2     0    0.072278   -0.161756    5.293927    5.294455    5.147584    5.294455
 2     0    sc          0.000000    6.300000    6.147584    6.147584    6.300000
 3     0    0.001670   -0.430594    4.121119    4.095465    4.102416    4.121119
 4     0    0.000289   -0.784047    5.088586    5.063318    5.077979    5.088586

 Harris energy:
 sumev=      -11.347235  val*vef=    -111.863199   sumtv=     100.515964
 sumec=        0.000000  cor*vef=       0.000000   ttcor=   33016.648880
 rhoeps=    -770.259057     utot=  -63494.686957    ehar=  -31147.781170

 srhov:     -3.192138   -108.682267   -111.874405 sumev=  -11.347235   sumtv=  100.527170

 Kohn-Sham energy:
 sumtv=      100.527170  sumtc=     33016.648880   ekin=    33117.176051
 rhoep=     -770.259786   utot=    -63494.697423   ehks=   -31147.781157
  
 mixing: mode=B  nmix=4  beta=1  elind=.112
 mixrho:  sought 4 iter from file mixm; read 4.  RMS DQ=2.30e-4  last it=2.07e-4
 broyj:  ir=4  dxmax=0.0019  gmax=0.0032  wc=1
 unscreened rms difference:  smooth  0.000064   local  0.000161
   screened rms difference:  smooth  0.000053   local  0.000161   tot  0.000230

 iors  : write restart file (binary, mesh density)

   it  5  of 80    ehf=  -31147.781170   ehk=  -31147.781157
 From last iter    ehf=  -31147.781156   ehk=  -31147.781145
 diffe(q)= -0.000014 (0.000230)    tol= 0.000010 (0.000100)   more=T
i nk=8 ehf=-31147.7811697 ehk=-31147.7811575

 --- BNDFP:  begin iteration 6 of 80 ---

 Average es pot at rmt = 0.128408  avg sphere pot = 0.241571   vconst = -0.128408
 smooth rhoves      2.680339   charge     4.568257
 smooth rhoeps =   -1.397150   rhomu =   -1.397281  avg vxc =   -0.335374 

 elocp:

 Fit local orbitals to sm hankels, species Cs, rmt=4.939085
  l  type    Pnu      Eval        K.E.       Rsm       Eh      Q(r>rmt)    Fit K.E.
  1  low    5.947   -0.915233   -0.619430   2.33009  -2.30125   0.01412   -0.619430 

 locpot:

 site  1  z= 55.0  rmt= 4.93908  nr=1261  a=0.010  nlml=25  rg=1.235  Vfloat=T
 sm core charge = 0.037439 (sphere) + 0.000473 (spillout) = 0.037912
 potential shift to crystal energy zero:    0.000006

 site  2  z= 55.0  rmt= 4.93908  nr=1261  a=0.010  nlml=25  rg=1.235  Vfloat=T
 sm core charge = 0.037439 (sphere) + 0.000473 (spillout) = 0.037912
 potential shift to crystal energy zero:    0.000009

 Energy terms:             smooth           local            total
   rhoval*vef             -3.203178      -108.671225      -111.874403
   rhoval*ves            -15.328356       -81.109224       -96.437579
   psnuc*ves              20.689034   -126913.648516   -126892.959482
   utot                    2.680339    -63497.378870    -63494.698531
   rho*exc                -1.397150      -768.862672      -770.259823
   rho*vxc                -1.397281     -1003.908026     -1005.305307
   valence chg             4.568257         9.431743        14.000000
   core charge            96.000000         0.000000        96.000000

 Charges:  valence    14.00000   cores    96.00000   nucleii  -110.00000
    hom background     0.00000   deviation from neutrality:      0.00000

 sugcut:  make orbital-dependent cutoffs for local orbitals, tol=1.0e-16
 spec      l    rsm    eh     gmax    last term   cutoff
  Cs       1    2.33  -2.30   5.327    1.19E-16    3959 
 

 Start first of two band passes ...
 bndfp:  kpt 1 of 35, k=  0.00000  0.00000  0.00000
 -0.9192 -0.9192 -0.9192 -0.9120 -0.9120 -0.9120 -0.2549 -0.0843 -0.0843
 bndfp:  kpt 11 of 35, k=  0.37500  0.25000  0.00000
 -0.9208 -0.9191 -0.9170 -0.9141 -0.9140 -0.9123 -0.1824 -0.1160 -0.0650
 bndfp:  kpt 21 of 35, k=  0.37500  0.25000  0.12500
 -0.9205 -0.9192 -0.9175 -0.9142 -0.9137 -0.9125 -0.1770 -0.1109 -0.0638
 bndfp:  kpt 31 of 35, k=  0.50000  0.50000  0.25000
 -0.9205 -0.9205 -0.9173 -0.9150 -0.9134 -0.9134 -0.1036 -0.1036 -0.0696

 BZWTS : --- Tetrahedron Integration ---
 BZINTS: Fermi energy:     -0.131937;  14.000000 electrons;  D(Ef):   42.042
         Sum occ. bands:  -11.3460914  incl. Bloechl correction:   -0.003531

 Saved qp weights ...
 Start second band pass ...
 bndfp:  kpt 1 of 35, k=  0.00000  0.00000  0.00000
 -0.9192 -0.9192 -0.9192 -0.9120 -0.9120 -0.9120 -0.2549 -0.0843 -0.0843
 bndfp:  kpt 11 of 35, k=  0.37500  0.25000  0.00000
 -0.9208 -0.9191 -0.9170 -0.9141 -0.9140 -0.9123 -0.1824 -0.1160 -0.0650
 bndfp:  kpt 21 of 35, k=  0.37500  0.25000  0.12500
 -0.9205 -0.9192 -0.9175 -0.9142 -0.9137 -0.9125 -0.1770 -0.1109 -0.0638
 bndfp:  kpt 31 of 35, k=  0.50000  0.50000  0.25000
 -0.9205 -0.9205 -0.9173 -0.9150 -0.9134 -0.9134 -0.1036 -0.1036 -0.0696

 BZWTS : --- Tetrahedron Integration ---
 BZINTS: Fermi energy:     -0.131937;  14.000000 electrons;  D(Ef):   42.042
         Sum occ. bands:  -11.3460914  incl. Bloechl correction:   -0.003531

 Saved qp weights ...

 mkrout:  Qtrue      sm,loc       local
   1    6.571188    1.860502    4.710686
   2    6.546541    1.815957    4.730584

 Symmetrize density..

 Make new boundary conditions for phi,phidot..

 site    1   species   1:Cs      
 l  idmod     ql         ebar        pold        ptry        pfree        pnew
 0     0    0.415773   -0.180181    6.627854    6.628326    6.500000    6.628326
 1     0    0.118326   -0.176457    6.500000    6.243471    6.250000    6.500000
 1     0    sc         -0.916306    5.946767    5.946778    5.250000   15.946778
 2     0    0.062848   -0.166164    5.289644    5.289421    5.147584    5.289421
 2     0    sc          0.000000    6.300000    6.147584    6.147584    6.300000
 3     0    0.001799   -0.409240    4.121119    4.097131    4.102416    4.121119
 4     0    0.000323   -0.762932    5.088586    5.063837    5.077979    5.088586

 site    2   species   1:Cs      
 l  idmod     ql         ebar        pold        ptry        pfree        pnew
 0     0    0.377884   -0.184786    6.618261    6.617737    6.500000    6.617737
 1     0    0.122396   -0.175011    6.500000    6.244064    6.250000    6.500000
 1     0    sc         -0.913972    5.946742    5.946728    5.250000   15.946728
 2     0    0.072515   -0.161439    5.294455    5.294568    5.147584    5.294568
 2     0    sc          0.000000    6.300000    6.147584    6.147584    6.300000
 3     0    0.001667   -0.430385    4.121119    4.095478    4.102416    4.121119
 4     0    0.000297   -0.788409    5.088586    5.063213    5.077979    5.088586

 Harris energy:
 sumev=      -11.346091  val*vef=    -111.874403   sumtv=     100.528312
 sumec=        0.000000  cor*vef=       0.000000   ttcor=   33016.648880
 rhoeps=    -770.259823     utot=  -63494.698531    ehar=  -31147.781161

 srhov:     -3.191937   -108.676438   -111.868375 sumev=  -11.346091   sumtv=  100.522283

 Kohn-Sham energy:
 sumtv=      100.522283  sumtc=     33016.648880   ekin=    33117.171164
 rhoep=     -770.259431   utot=    -63494.692873   ehks=   -31147.781141
  
 mixing: mode=B  nmix=4  beta=1  elind=.112
 mixrho:  sought 4 iter from file mixm; read 5.  RMS DQ=2.73e-4  last it=2.30e-4
 broyj:  ir=4  dxmax=0.012  gmax=0.0039  wc=1
 unscreened rms difference:  smooth  0.000079   local  0.000199
   screened rms difference:  smooth  0.000064   local  0.000199   tot  0.000273

 iors  : write restart file (binary, mesh density)

   it  6  of 80    ehf=  -31147.781161   ehk=  -31147.781141
 From last iter    ehf=  -31147.781170   ehk=  -31147.781157
 diffe(q)=  0.000008 (0.000273)    tol= 0.000010 (0.000100)   more=T
i nk=8 ehf=-31147.7811612 ehk=-31147.7811406

 --- BNDFP:  begin iteration 7 of 80 ---

 Average es pot at rmt = 0.128346  avg sphere pot = 0.241625   vconst = -0.128346
 smooth rhoves      2.676217   charge     4.561286
 smooth rhoeps =   -1.394402   rhomu =   -1.394546  avg vxc =   -0.335273 

 elocp:

 Fit local orbitals to sm hankels, species Cs, rmt=4.939085
  l  type    Pnu      Eval        K.E.       Rsm       Eh      Q(r>rmt)    Fit K.E.
  1  low    5.947   -0.915140   -0.619343   2.33013  -2.30110   0.01412   -0.619343 

 locpot:

 site  1  z= 55.0  rmt= 4.93908  nr=1261  a=0.010  nlml=25  rg=1.235  Vfloat=T
 sm core charge = 0.037439 (sphere) + 0.000473 (spillout) = 0.037912
 potential shift to crystal energy zero:    0.000007

 site  2  z= 55.0  rmt= 4.93908  nr=1261  a=0.010  nlml=25  rg=1.235  Vfloat=T
 sm core charge = 0.037439 (sphere) + 0.000473 (spillout) = 0.037912
 potential shift to crystal energy zero:    0.000007

 Energy terms:             smooth           local            total
   rhoval*vef             -3.194989      -108.697465      -111.892454
   rhoval*ves            -15.317490       -81.136901       -96.454391
   psnuc*ves              20.669925   -126913.649159   -126892.979234
   utot                    2.676217    -63497.393030    -63494.716813
   rho*exc                -1.394402      -768.866634      -770.261036
   rho*vxc                -1.394546     -1003.913186     -1005.307732
   valence chg             4.561286         9.438714        14.000000
   core charge            96.000000         0.000000        96.000000

 Charges:  valence    14.00000   cores    96.00000   nucleii  -110.00000
    hom background     0.00000   deviation from neutrality:      0.00000

 sugcut:  make orbital-dependent cutoffs for local orbitals, tol=1.0e-16
 spec      l    rsm    eh     gmax    last term   cutoff
  Cs       1    2.33  -2.30   5.327    1.19E-16    3959 
 

 Start first of two band passes ...
 bndfp:  kpt 1 of 35, k=  0.00000  0.00000  0.00000
 -0.9195 -0.9195 -0.9195 -0.9116 -0.9116 -0.9116 -0.2549 -0.0843 -0.0843
 bndfp:  kpt 11 of 35, k=  0.37500  0.25000  0.00000
 -0.9210 -0.9194 -0.9176 -0.9135 -0.9132 -0.9119 -0.1824 -0.1160 -0.0650
 bndfp:  kpt 21 of 35, k=  0.37500  0.25000  0.12500
 -0.9208 -0.9196 -0.9180 -0.9135 -0.9131 -0.9121 -0.1770 -0.1109 -0.0638
 bndfp:  kpt 31 of 35, k=  0.50000  0.50000  0.25000
 -0.9207 -0.9207 -0.9180 -0.9140 -0.9129 -0.9129 -0.1036 -0.1036 -0.0696

 BZWTS : --- Tetrahedron Integration ---
 BZINTS: Fermi energy:     -0.131925;  14.000000 electrons;  D(Ef):   42.012
         Sum occ. bands:  -11.3446607  incl. Bloechl correction:   -0.003524

 Saved qp weights ...
 Start second band pass ...
 bndfp:  kpt 1 of 35, k=  0.00000  0.00000  0.00000
 -0.9195 -0.9195 -0.9195 -0.9116 -0.9116 -0.9116 -0.2549 -0.0843 -0.0843
 bndfp:  kpt 11 of 35, k=  0.37500  0.25000  0.00000
 -0.9210 -0.9194 -0.9176 -0.9135 -0.9132 -0.9119 -0.1824 -0.1160 -0.0650
 bndfp:  kpt 21 of 35, k=  0.37500  0.25000  0.12500
 -0.9208 -0.9196 -0.9180 -0.9135 -0.9131 -0.9121 -0.1770 -0.1109 -0.0638
 bndfp:  kpt 31 of 35, k=  0.50000  0.50000  0.25000
 -0.9207 -0.9207 -0.9180 -0.9140 -0.9129 -0.9129 -0.1036 -0.1036 -0.0696

 BZWTS : --- Tetrahedron Integration ---
 BZINTS: Fermi energy:     -0.131925;  14.000000 electrons;  D(Ef):   42.012
         Sum occ. bands:  -11.3446607  incl. Bloechl correction:   -0.003524

 Saved qp weights ...

 mkrout:  Qtrue      sm,loc       local
   1    6.545797    1.834032    4.711764
   2    6.571855    1.842964    4.728891

 Symmetrize density..

 Make new boundary conditions for phi,phidot..

 site    1   species   1:Cs      
 l  idmod     ql         ebar        pold        ptry        pfree        pnew
 0     0    0.377177   -0.184789    6.628326    6.617214    6.500000    6.617214
 1     0    0.122388   -0.174980    6.500000    6.243913    6.250000    6.500000
 1     0    sc         -0.913012    5.946778    5.946707    5.250000   15.946707
 2     0    0.072386   -0.161443    5.289421    5.294102    5.147584    5.294102
 2     0    sc          0.000000    6.300000    6.147584    6.147584    6.300000
 3     0    0.001665   -0.429744    4.121119    4.095519    4.102416    4.121119
 4     0    0.000313   -0.796240    5.088586    5.063023    5.077979    5.088586

 site    2   species   1:Cs      
 l  idmod     ql         ebar        pold        ptry        pfree        pnew
 0     0    0.416451   -0.180178    6.617737    6.628743    6.500000    6.628743
 1     0    0.118334   -0.176496    6.500000    6.243578    6.250000    6.500000
 1     0    sc         -0.917025    5.946728    5.946794    5.250000   15.946794
 2     0    0.062952   -0.166169    5.294568    5.289802    5.147584    5.289802
 2     0    sc          0.000000    6.300000    6.147584    6.147584    6.300000
 3     0    0.001803   -0.409864    4.121119    4.097091    4.102416    4.121119
 4     0    0.000307   -0.753856    5.088586    5.064065    5.077979    5.088586

 Harris energy:
 sumev=      -11.344661  val*vef=    -111.892454   sumtv=     100.547794
 sumec=        0.000000  cor*vef=       0.000000   ttcor=   33016.648880
 rhoeps=    -770.261036     utot=  -63494.716813    ehar=  -31147.781175

 srhov:     -3.190555   -108.668980   -111.859535 sumev=  -11.344661   sumtv=  100.514874

 Kohn-Sham energy:
 sumtv=      100.514874  sumtc=     33016.648880   ekin=    33117.163755
 rhoep=     -770.258902   utot=    -63494.685990   ehks=   -31147.781138
  
 mixing: mode=B  nmix=4  beta=1  elind=.112
 mixrho:  sought 4 iter from file mixm; read 5.  RMS DQ=7.65e-4  last it=2.73e-4
 broyj:  ir=4  dxmax=0.0054  gmax=0.0092  wc=1
 unscreened rms difference:  smooth  0.000187   local  0.000472
   screened rms difference:  smooth  0.000169   local  0.000472   tot  0.000765

 iors  : write restart file (binary, mesh density)

   it  7  of 80    ehf=  -31147.781175   ehk=  -31147.781138
 From last iter    ehf=  -31147.781161   ehk=  -31147.781141
 diffe(q)= -0.000014 (0.000765)    tol= 0.000010 (0.000100)   more=T
i nk=8 ehf=-31147.7811751 ehk=-31147.7811382

 --- BNDFP:  begin iteration 8 of 80 ---

 Average es pot at rmt = 0.128324  avg sphere pot = 0.241662   vconst = -0.128324
 smooth rhoves      2.673363   charge     4.558954
 smooth rhoeps =   -1.392801   rhomu =   -1.392938  avg vxc =   -0.335279 

 elocp:

 Fit local orbitals to sm hankels, species Cs, rmt=4.939085
  l  type    Pnu      Eval        K.E.       Rsm       Eh      Q(r>rmt)    Fit K.E.
  1  low    5.947   -0.915019   -0.619204   2.33024  -2.30136   0.01412   -0.619204 

 locpot:

 site  1  z= 55.0  rmt= 4.93908  nr=1261  a=0.010  nlml=25  rg=1.235  Vfloat=T
 sm core charge = 0.037439 (sphere) + 0.000473 (spillout) = 0.037912
 potential shift to crystal energy zero:    0.000008

 site  2  z= 55.0  rmt= 4.93908  nr=1261  a=0.010  nlml=25  rg=1.235  Vfloat=T
 sm core charge = 0.037439 (sphere) + 0.000473 (spillout) = 0.037912
 potential shift to crystal energy zero:    0.000008

 Energy terms:             smooth           local            total
   rhoval*vef             -3.190315      -108.682947      -111.873262
   rhoval*ves            -15.317071       -81.119469       -96.436539
   psnuc*ves              20.663796   -126913.621460   -126892.957664
   utot                    2.673363    -63497.370464    -63494.697102
   rho*exc                -1.392801      -768.866921      -770.259722
   rho*vxc                -1.392938     -1003.913502     -1005.306441
   valence chg             4.558954         9.441046        14.000000
   core charge            96.000000         0.000000        96.000000

 Charges:  valence    14.00000   cores    96.00000   nucleii  -110.00000
    hom background     0.00000   deviation from neutrality:      0.00000

 sugcut:  make orbital-dependent cutoffs for local orbitals, tol=1.0e-16
 spec      l    rsm    eh     gmax    last term   cutoff
  Cs       1    2.33  -2.30   5.326    1.18E-16    3959 
 

 Start first of two band passes ...
 bndfp:  kpt 1 of 35, k=  0.00000  0.00000  0.00000
 -0.9192 -0.9192 -0.9192 -0.9121 -0.9121 -0.9121 -0.2549 -0.0843 -0.0843
 bndfp:  kpt 11 of 35, k=  0.37500  0.25000  0.00000
 -0.9208 -0.9191 -0.9169 -0.9142 -0.9141 -0.9124 -0.1824 -0.1160 -0.0650
 bndfp:  kpt 21 of 35, k=  0.37500  0.25000  0.12500
 -0.9205 -0.9192 -0.9174 -0.9143 -0.9138 -0.9126 -0.1770 -0.1109 -0.0638
 bndfp:  kpt 31 of 35, k=  0.50000  0.50000  0.25000
 -0.9205 -0.9205 -0.9172 -0.9152 -0.9135 -0.9135 -0.1037 -0.1036 -0.0696

 BZWTS : --- Tetrahedron Integration ---
 BZINTS: Fermi energy:     -0.131956;  14.000000 electrons;  D(Ef):   42.076
         Sum occ. bands:  -11.3465032  incl. Bloechl correction:   -0.003537

 Saved qp weights ...
 Start second band pass ...
 bndfp:  kpt 1 of 35, k=  0.00000  0.00000  0.00000
 -0.9192 -0.9192 -0.9192 -0.9121 -0.9121 -0.9121 -0.2549 -0.0843 -0.0843
 bndfp:  kpt 11 of 35, k=  0.37500  0.25000  0.00000
 -0.9208 -0.9191 -0.9169 -0.9142 -0.9141 -0.9124 -0.1824 -0.1160 -0.0650
 bndfp:  kpt 21 of 35, k=  0.37500  0.25000  0.12500
 -0.9205 -0.9192 -0.9174 -0.9143 -0.9138 -0.9126 -0.1770 -0.1109 -0.0638
 bndfp:  kpt 31 of 35, k=  0.50000  0.50000  0.25000
 -0.9205 -0.9205 -0.9172 -0.9152 -0.9135 -0.9135 -0.1037 -0.1036 -0.0696

 BZWTS : --- Tetrahedron Integration ---
 BZINTS: Fermi energy:     -0.131956;  14.000000 electrons;  D(Ef):   42.076
         Sum occ. bands:  -11.3465032  incl. Bloechl correction:   -0.003537

 Saved qp weights ...

 mkrout:  Qtrue      sm,loc       local
   1    6.546676    1.802106    4.744570
   2    6.571020    1.873916    4.697104

 Symmetrize density..

 Make new boundary conditions for phi,phidot..

 site    1   species   1:Cs      
 l  idmod     ql         ebar        pold        ptry        pfree        pnew
 0     0    0.377989   -0.184865    6.617214    6.617810    6.500000    6.617810
 1     0    0.122315   -0.175110    6.500000    6.244083    6.250000    6.500000
 1     0    sc         -0.914157    5.946707    5.946731    5.250000   15.946731
 2     0    0.072743   -0.161261    5.294102    5.294958    5.147584    5.294958
 2     0    sc          0.000000    6.300000    6.147584    6.147584    6.300000
 3     0    0.001670   -0.430716    4.121119    4.095460    4.102416    4.121119
 4     0    0.000283   -0.782807    5.088586    5.063350    5.077979    5.088586

 site    2   species   1:Cs      
 l  idmod     ql         ebar        pold        ptry        pfree        pnew
 0     0    0.415636   -0.180137    6.628743    6.628218    6.500000    6.628218
 1     0    0.118427   -0.176375    6.500000    6.243462    6.250000    6.500000
 1     0    sc         -0.916184    5.946794    5.946776    5.250000   15.946776
 2     0    0.062605   -0.166435    5.289802    5.288952    5.147584    5.288952
 2     0    sc          0.000000    6.300000    6.147584    6.147584    6.300000
 3     0    0.001796   -0.409002    4.121119    4.097145    4.102416    4.121119
 4     0    0.000338   -0.769292    5.088586    5.063679    5.077979    5.088586

 Harris energy:
 sumev=      -11.346503  val*vef=    -111.873262   sumtv=     100.526759
 sumec=        0.000000  cor*vef=       0.000000   ttcor=   33016.648880
 rhoeps=    -770.259722     utot=  -63494.697102    ehar=  -31147.781184

 srhov:     -3.188806   -108.680931   -111.869737 sumev=  -11.346503   sumtv=  100.523234

 Kohn-Sham energy:
 sumtv=      100.523234  sumtc=     33016.648880   ekin=    33117.172114
 rhoep=     -770.259505   utot=    -63494.693780   ehks=   -31147.781171
  
 mixing: mode=B  nmix=4  beta=1  elind=.112
 mixrho:  sought 4 iter from file mixm; read 5.  RMS DQ=7.12e-4  last it=7.65e-4
 broyj:  ir=4  dxmax=0.0053  gmax=0.0084  wc=1
 unscreened rms difference:  smooth  0.000168   local  0.000433
   screened rms difference:  smooth  0.000155   local  0.000433   tot  0.000712

 iors  : write restart file (binary, mesh density)

   it  8  of 80    ehf=  -31147.781184   ehk=  -31147.781171
 From last iter    ehf=  -31147.781175   ehk=  -31147.781138
 diffe(q)= -0.000009 (0.000712)    tol= 0.000010 (0.000100)   more=T
i nk=8 ehf=-31147.7811843 ehk=-31147.7811707

 --- BNDFP:  begin iteration 9 of 80 ---

 Average es pot at rmt = 0.128346  avg sphere pot = 0.241639   vconst = -0.128346
 smooth rhoves      2.676267   charge     4.561328
 smooth rhoeps =   -1.394381   rhomu =   -1.394524  avg vxc =   -0.335278 

 elocp:

 Fit local orbitals to sm hankels, species Cs, rmt=4.939085
  l  type    Pnu      Eval        K.E.       Rsm       Eh      Q(r>rmt)    Fit K.E.
  1  low    5.947   -0.915170   -0.619358   2.33015  -2.30140   0.01412   -0.619358 

 locpot:

 site  1  z= 55.0  rmt= 4.93908  nr=1261  a=0.010  nlml=25  rg=1.235  Vfloat=T
 sm core charge = 0.037439 (sphere) + 0.000473 (spillout) = 0.037912
 potential shift to crystal energy zero:    0.000008

 site  2  z= 55.0  rmt= 4.93908  nr=1261  a=0.010  nlml=25  rg=1.235  Vfloat=T
 sm core charge = 0.037439 (sphere) + 0.000473 (spillout) = 0.037912
 potential shift to crystal energy zero:    0.000008

 Energy terms:             smooth           local            total
   rhoval*vef             -3.195032      -108.678925      -111.873957
   rhoval*ves            -15.317677       -81.119500       -96.437177
   psnuc*ves              20.670211   -126913.628717   -126892.958507
   utot                    2.676267    -63497.374108    -63494.697842
   rho*exc                -1.394381      -768.865395      -770.259775
   rho*vxc                -1.394524     -1003.911539     -1005.306064
   valence chg             4.561328         9.438672        14.000000
   core charge            96.000000         0.000000        96.000000

 Charges:  valence    14.00000   cores    96.00000   nucleii  -110.00000
    hom background     0.00000   deviation from neutrality:      0.00000

 sugcut:  make orbital-dependent cutoffs for local orbitals, tol=1.0e-16
 spec      l    rsm    eh     gmax    last term   cutoff
  Cs       1    2.33  -2.30   5.327    1.19E-16    3959 
 

 Start first of two band passes ...
 bndfp:  kpt 1 of 35, k=  0.00000  0.00000  0.00000
 -0.9193 -0.9193 -0.9193 -0.9120 -0.9120 -0.9120 -0.2549 -0.0843 -0.0843
 bndfp:  kpt 11 of 35, k=  0.37500  0.25000  0.00000
 -0.9209 -0.9192 -0.9172 -0.9140 -0.9138 -0.9123 -0.1824 -0.1160 -0.0650
 bndfp:  kpt 21 of 35, k=  0.37500  0.25000  0.12500
 -0.9206 -0.9194 -0.9177 -0.9140 -0.9136 -0.9125 -0.1770 -0.1109 -0.0638
 bndfp:  kpt 31 of 35, k=  0.50000  0.50000  0.25000
 -0.9206 -0.9206 -0.9176 -0.9148 -0.9133 -0.9133 -0.1037 -0.1036 -0.0696

 BZWTS : --- Tetrahedron Integration ---
 BZINTS: Fermi energy:     -0.131947;  14.000000 electrons;  D(Ef):   42.035
         Sum occ. bands:  -11.3463896  incl. Bloechl correction:   -0.003529

 Saved qp weights ...
 Start second band pass ...
 bndfp:  kpt 1 of 35, k=  0.00000  0.00000  0.00000
 -0.9193 -0.9193 -0.9193 -0.9120 -0.9120 -0.9120 -0.2549 -0.0843 -0.0843
 bndfp:  kpt 11 of 35, k=  0.37500  0.25000  0.00000
 -0.9209 -0.9192 -0.9172 -0.9140 -0.9138 -0.9123 -0.1824 -0.1160 -0.0650
 bndfp:  kpt 21 of 35, k=  0.37500  0.25000  0.12500
 -0.9206 -0.9194 -0.9177 -0.9140 -0.9136 -0.9125 -0.1770 -0.1109 -0.0638
 bndfp:  kpt 31 of 35, k=  0.50000  0.50000  0.25000
 -0.9206 -0.9206 -0.9176 -0.9148 -0.9133 -0.9133 -0.1037 -0.1036 -0.0696

 BZWTS : --- Tetrahedron Integration ---
 BZINTS: Fermi energy:     -0.131947;  14.000000 electrons;  D(Ef):   42.035
         Sum occ. bands:  -11.3463896  incl. Bloechl correction:   -0.003529

 Saved qp weights ...

 mkrout:  Qtrue      sm,loc       local
   1    6.546275    1.812016    4.734259
   2    6.571445    1.864183    4.707262

 Symmetrize density..

 Make new boundary conditions for phi,phidot..

 site    1   species   1:Cs      
 l  idmod     ql         ebar        pold        ptry        pfree        pnew
 0     0    0.377720   -0.184799    6.617810    6.617599    6.500000    6.617599
 1     0    0.122393   -0.175039    6.500000    6.244002    6.250000    6.500000
 1     0    sc         -0.913745    5.946731    5.946723    5.250000   15.946723
 2     0    0.072468   -0.161451    5.294958    5.294417    5.147584    5.294417
 2     0    sc          0.000000    6.300000    6.147584    6.147584    6.300000
 3     0    0.001668   -0.430463    4.121119    4.095468    4.102416    4.121119
 4     0    0.000292   -0.787116    5.088586    5.063242    5.077979    5.088586

 site    2   species   1:Cs      
 l  idmod     ql         ebar        pold        ptry        pfree        pnew
 0     0    0.415931   -0.180193    6.628218    6.628443    6.500000    6.628443
 1     0    0.118328   -0.176453    6.500000    6.243536    6.250000    6.500000
 1     0    sc         -0.916579    5.946776    5.946784    5.250000   15.946784
 2     0    0.062893   -0.166176    5.288952    5.289562    5.147584    5.289562
 2     0    sc          0.000000    6.300000    6.147584    6.147584    6.300000
 3     0    0.001799   -0.409122    4.121119    4.097147    4.102416    4.121119
 4     0    0.000328   -0.764631    5.088586    5.063798    5.077979    5.088586

 Harris energy:
 sumev=      -11.346390  val*vef=    -111.873957   sumtv=     100.527568
 sumec=        0.000000  cor*vef=       0.000000   ttcor=   33016.648880
 rhoeps=    -770.259775     utot=  -63494.697842    ehar=  -31147.781169

 srhov:     -3.189144   -108.680197   -111.869341 sumev=  -11.346390   sumtv=  100.522951

 Kohn-Sham energy:
 sumtv=      100.522951  sumtc=     33016.648880   ekin=    33117.171832
 rhoep=     -770.259485   utot=    -63494.693490   ehks=   -31147.781143
  
 mixing: mode=B  nmix=4  beta=1  elind=.112
 mixrho:  sought 4 iter from file mixm; read 5.  RMS DQ=1.04e-3  last it=7.12e-4
 broyj:  ir=4  dxmax=0.014  gmax=0.012  wc=1
 unscreened rms difference:  smooth  0.000242   local  0.000636
   screened rms difference:  smooth  0.000227   local  0.000636   tot  0.001037

 iors  : write restart file (binary, mesh density)

   it  9  of 80    ehf=  -31147.781169   ehk=  -31147.781143
 From last iter    ehf=  -31147.781184   ehk=  -31147.781171
 diffe(q)=  0.000016 (0.001037)    tol= 0.000010 (0.000100)   more=T
i nk=8 ehf=-31147.7811686 ehk=-31147.7811428

 --- BNDFP:  begin iteration 10 of 80 ---

 Average es pot at rmt = 0.128314  avg sphere pot = 0.241673   vconst = -0.128314
 smooth rhoves      2.672526   charge     4.558051
 smooth rhoeps =   -1.392344   rhomu =   -1.392471  avg vxc =   -0.335273 

 elocp:

 Fit local orbitals to sm hankels, species Cs, rmt=4.939085
  l  type    Pnu      Eval        K.E.       Rsm       Eh      Q(r>rmt)    Fit K.E.
  1  low    5.947   -0.915162   -0.619354   2.33014  -2.30130   0.01412   -0.619354 

 locpot:

 site  1  z= 55.0  rmt= 4.93908  nr=1261  a=0.010  nlml=25  rg=1.235  Vfloat=T
 sm core charge = 0.037439 (sphere) + 0.000473 (spillout) = 0.037912
 potential shift to crystal energy zero:    0.000009

 site  2  z= 55.0  rmt= 4.93908  nr=1261  a=0.010  nlml=25  rg=1.235  Vfloat=T
 sm core charge = 0.037439 (sphere) + 0.000473 (spillout) = 0.037912
 potential shift to crystal energy zero:    0.000008

 Energy terms:             smooth           local            total
   rhoval*vef             -3.189038      -108.683199      -111.872237
   rhoval*ves            -15.316072       -81.119529       -96.435601
   psnuc*ves              20.661124   -126913.617614   -126892.956490
   utot                    2.672526    -63497.368571    -63494.696045
   rho*exc                -1.392344      -768.867297      -770.259641
   rho*vxc                -1.392471     -1003.913985     -1005.306456
   valence chg             4.558051         9.441949        14.000000
   core charge            96.000000         0.000000        96.000000

 Charges:  valence    14.00000   cores    96.00000   nucleii  -110.00000
    hom background     0.00000   deviation from neutrality:      0.00000

 sugcut:  make orbital-dependent cutoffs for local orbitals, tol=1.0e-16
 spec      l    rsm    eh     gmax    last term   cutoff
  Cs       1    2.33  -2.30   5.327    1.19E-16    3959 
 

 Start first of two band passes ...
 bndfp:  kpt 1 of 35, k=  0.00000  0.00000  0.00000
 -0.9191 -0.9191 -0.9191 -0.9122 -0.9122 -0.9122 -0.2550 -0.0843 -0.0843
 bndfp:  kpt 11 of 35, k=  0.37500  0.25000  0.00000
 -0.9207 -0.9189 -0.9165 -0.9146 -0.9144 -0.9125 -0.1824 -0.1160 -0.0650
 bndfp:  kpt 21 of 35, k=  0.37500  0.25000  0.12500
 -0.9204 -0.9190 -0.9171 -0.9146 -0.9140 -0.9127 -0.1770 -0.1109 -0.0638
 bndfp:  kpt 31 of 35, k=  0.50000  0.50000  0.25000
 -0.9204 -0.9204 -0.9165 -0.9159 -0.9136 -0.9136 -0.1037 -0.1036 -0.0696

 BZWTS : --- Tetrahedron Integration ---
 BZINTS: Fermi energy:     -0.131962;  14.000000 electrons;  D(Ef):   42.064
         Sum occ. bands:  -11.3466007  incl. Bloechl correction:   -0.003538

 Saved qp weights ...
 Start second band pass ...
 bndfp:  kpt 1 of 35, k=  0.00000  0.00000  0.00000
 -0.9191 -0.9191 -0.9191 -0.9122 -0.9122 -0.9122 -0.2550 -0.0843 -0.0843
 bndfp:  kpt 11 of 35, k=  0.37500  0.25000  0.00000
 -0.9207 -0.9189 -0.9165 -0.9146 -0.9144 -0.9125 -0.1824 -0.1160 -0.0650
 bndfp:  kpt 21 of 35, k=  0.37500  0.25000  0.12500
 -0.9204 -0.9190 -0.9171 -0.9146 -0.9140 -0.9127 -0.1770 -0.1109 -0.0638
 bndfp:  kpt 31 of 35, k=  0.50000  0.50000  0.25000
 -0.9204 -0.9204 -0.9165 -0.9159 -0.9136 -0.9136 -0.1037 -0.1036 -0.0696

 BZWTS : --- Tetrahedron Integration ---
 BZINTS: Fermi energy:     -0.131962;  14.000000 electrons;  D(Ef):   42.064
         Sum occ. bands:  -11.3466007  incl. Bloechl correction:   -0.003538

 Saved qp weights ...

 mkrout:  Qtrue      sm,loc       local
   1    6.569978    1.840437    4.729541
   2    6.547725    1.835882    4.711843

 Symmetrize density..

 Make new boundary conditions for phi,phidot..

 site    1   species   1:Cs      
 l  idmod     ql         ebar        pold        ptry        pfree        pnew
 0     0    0.414698   -0.180269    6.617599    6.627694    6.500000    6.627694
 1     0    0.118224   -0.176636    6.500000    6.243221    6.250000    6.500000
 1     0    sc         -0.915471    5.946723    5.946760    5.250000   15.946760
 2     0    0.063082   -0.165796    5.294417    5.289544    5.147584    5.289544
 2     0    sc          0.000000    6.300000    6.147584    6.147584    6.300000
 3     0    0.001799   -0.409757    4.121119    4.097090    4.102416    4.121119
 4     0    0.000303   -0.754314    5.088586    5.064053    5.077979    5.088586

 site    2   species   1:Cs      
 l  idmod     ql         ebar        pold        ptry        pfree        pnew
 0     0    0.378899   -0.184718    6.628443    6.618371    6.500000    6.618371
 1     0    0.122515   -0.174865    6.500000    6.244316    6.250000    6.500000
 1     0    sc         -0.914887    5.946784    5.946747    5.250000   15.946747
 2     0    0.072293   -0.161769    5.289562    5.294529    5.147584    5.294529
 2     0    sc          0.000000    6.300000    6.147584    6.147584    6.300000
 3     0    0.001667   -0.429880    4.121119    4.095518    4.102416    4.121119
 4     0    0.000317   -0.795441    5.088586    5.063044    5.077979    5.088586

 Harris energy:
 sumev=      -11.346601  val*vef=    -111.872237   sumtv=     100.525636
 sumec=        0.000000  cor*vef=       0.000000   ttcor=   33016.648880
 rhoeps=    -770.259641     utot=  -63494.696045    ehar=  -31147.781170

 srhov:     -3.189375   -108.680848   -111.870224 sumev=  -11.346601   sumtv=  100.523623

 Kohn-Sham energy:
 sumtv=      100.523623  sumtc=     33016.648880   ekin=    33117.172503
 rhoep=     -770.259537   utot=    -63494.694128   ehks=   -31147.781162
  
 mixing: mode=B  nmix=4  beta=1  elind=.112
 mixrho:  sought 4 iter from file mixm; read 5.  RMS DQ=2.46e-4  last it=1.04e-3
 broyj:  ir=4  dxmax=0.0018  gmax=3e-3  wc=1
 unscreened rms difference:  smooth  0.000065   local  0.000152
   screened rms difference:  smooth  0.000055   local  0.000152   tot  0.000246

 iors  : write restart file (binary, mesh density)

   it 10  of 80    ehf=  -31147.781170   ehk=  -31147.781162
 From last iter    ehf=  -31147.781169   ehk=  -31147.781143
 diffe(q)= -0.000001 (0.000246)    tol= 0.000010 (0.000100)   more=T
i nk=8 ehf=-31147.7811699 ehk=-31147.7811616

 --- BNDFP:  begin iteration 11 of 80 ---

 Average es pot at rmt = 0.128319  avg sphere pot = 0.241669   vconst = -0.128319
 smooth rhoves      2.672766   charge     4.558515
 smooth rhoeps =   -1.392493   rhomu =   -1.392623  avg vxc =   -0.335282 

 elocp:

 Fit local orbitals to sm hankels, species Cs, rmt=4.939085
  l  type    Pnu      Eval        K.E.       Rsm       Eh      Q(r>rmt)    Fit K.E.
  1  low    5.947   -0.915179   -0.619362   2.33016  -2.30151   0.01412   -0.619362 

 locpot:

 site  1  z= 55.0  rmt= 4.93908  nr=1261  a=0.010  nlml=25  rg=1.235  Vfloat=T
 sm core charge = 0.037439 (sphere) + 0.000473 (spillout) = 0.037912
 potential shift to crystal energy zero:    0.000008

 site  2  z= 55.0  rmt= 4.93908  nr=1261  a=0.010  nlml=25  rg=1.235  Vfloat=T
 sm core charge = 0.037439 (sphere) + 0.000473 (spillout) = 0.037912
 potential shift to crystal energy zero:    0.000008

 Energy terms:             smooth           local            total
   rhoval*vef             -3.189474      -108.680620      -111.870093
   rhoval*ves            -15.317019       -81.116583       -96.433602
   psnuc*ves              20.662550   -126913.616615   -126892.954065
   utot                    2.672766    -63497.366599    -63494.693833
   rho*exc                -1.392493      -768.867004      -770.259498
   rho*vxc                -1.392623     -1003.913602     -1005.306224
   valence chg             4.558515         9.441485        14.000000
   core charge            96.000000         0.000000        96.000000

 Charges:  valence    14.00000   cores    96.00000   nucleii  -110.00000
    hom background     0.00000   deviation from neutrality:      0.00000

 sugcut:  make orbital-dependent cutoffs for local orbitals, tol=1.0e-16
 spec      l    rsm    eh     gmax    last term   cutoff
  Cs       1    2.33  -2.30   5.327    1.19E-16    3959 
 

 Start first of two band passes ...
 bndfp:  kpt 1 of 35, k=  0.00000  0.00000  0.00000
 -0.9191 -0.9191 -0.9191 -0.9123 -0.9123 -0.9123 -0.2550 -0.0843 -0.0843
 bndfp:  kpt 11 of 35, k=  0.37500  0.25000  0.00000
 -0.9207 -0.9189 -0.9165 -0.9146 -0.9144 -0.9125 -0.1824 -0.1160 -0.0650
 bndfp:  kpt 21 of 35, k=  0.37500  0.25000  0.12500
 -0.9204 -0.9191 -0.9171 -0.9146 -0.9140 -0.9127 -0.1770 -0.1109 -0.0638
 bndfp:  kpt 31 of 35, k=  0.50000  0.50000  0.25000
 -0.9204 -0.9204 -0.9165 -0.9159 -0.9136 -0.9136 -0.1037 -0.1036 -0.0696

 BZWTS : --- Tetrahedron Integration ---
 BZINTS: Fermi energy:     -0.131969;  14.000000 electrons;  D(Ef):   42.072
         Sum occ. bands:  -11.3467980  incl. Bloechl correction:   -0.003541

 Saved qp weights ...
 Start second band pass ...
 bndfp:  kpt 1 of 35, k=  0.00000  0.00000  0.00000
 -0.9191 -0.9191 -0.9191 -0.9123 -0.9123 -0.9123 -0.2550 -0.0843 -0.0843
 bndfp:  kpt 11 of 35, k=  0.37500  0.25000  0.00000
 -0.9207 -0.9189 -0.9165 -0.9146 -0.9144 -0.9125 -0.1824 -0.1160 -0.0650
 bndfp:  kpt 21 of 35, k=  0.37500  0.25000  0.12500
 -0.9204 -0.9191 -0.9171 -0.9146 -0.9140 -0.9127 -0.1770 -0.1109 -0.0638
 bndfp:  kpt 31 of 35, k=  0.50000  0.50000  0.25000
 -0.9204 -0.9204 -0.9165 -0.9159 -0.9136 -0.9136 -0.1037 -0.1036 -0.0696

 BZWTS : --- Tetrahedron Integration ---
 BZINTS: Fermi energy:     -0.131969;  14.000000 electrons;  D(Ef):   42.072
         Sum occ. bands:  -11.3467980  incl. Bloechl correction:   -0.003541

 Saved qp weights ...

 mkrout:  Qtrue      sm,loc       local
   1    6.571184    1.859571    4.711614
   2    6.546522    1.816246    4.730275

 Symmetrize density..

 Make new boundary conditions for phi,phidot..

 site    1   species   1:Cs      
 l  idmod     ql         ebar        pold        ptry        pfree        pnew
 0     0    0.416653   -0.180173    6.627694    6.627598    6.500000    6.627598
 1     0    0.117151   -0.176742    6.500000    6.243067    6.250000    6.500000
 1     0    sc         -0.914863    5.946760    5.946747    5.250000   15.946747
 2     0    0.063295   -0.165720    5.289544    5.289393    5.147584    5.289393
 2     0    sc          0.000000    6.300000    6.147584    6.147584    6.300000
 3     0    0.001794   -0.409407    4.121119    4.097117    4.102416    4.121119
 4     0    0.000319   -0.762080    5.088586    5.063860    5.077979    5.088586

 site    2   species   1:Cs      
 l  idmod     ql         ebar        pold        ptry        pfree        pnew
 0     0    0.376921   -0.184854    6.618371    6.618399    6.500000    6.618399
 1     0    0.123593   -0.174780    6.500000    6.244463    6.250000    6.500000
 1     0    sc         -0.915529    5.946747    5.946761    5.250000   15.946761
 2     0    0.072099   -0.161813    5.294529    5.294743    5.147584    5.294743
 2     0    sc          0.000000    6.300000    6.147584    6.147584    6.300000
 3     0    0.001672   -0.430156    4.121119    4.095498    4.102416    4.121119
 4     0    0.000300   -0.789103    5.088586    5.063195    5.077979    5.088586

 Harris energy:
 sumev=      -11.346798  val*vef=    -111.870093   sumtv=     100.523295
 sumec=        0.000000  cor*vef=       0.000000   ttcor=   33016.648880
 rhoeps=    -770.259498     utot=  -63494.693833    ehar=  -31147.781155

 srhov:     -3.188816   -108.682609   -111.871425 sumev=  -11.346798   sumtv=  100.524627

 Kohn-Sham energy:
 sumtv=      100.524627  sumtc=     33016.648880   ekin=    33117.173507
 rhoep=     -770.259616   utot=    -63494.695041   ehks=   -31147.781150
  
 mixing: mode=B  nmix=4  beta=1  elind=.112
 mixrho:  sought 4 iter from file mixm; read 5.  RMS DQ=3.22e-4  last it=2.46e-4
 broyj:  ir=4  dxmax=0.0016  gmax=0.0038  wc=1
 unscreened rms difference:  smooth  0.000078   local  0.000196
   screened rms difference:  smooth  0.000071   local  0.000196   tot  0.000322

 iors  : write restart file (binary, mesh density)

   it 11  of 80    ehf=  -31147.781155   ehk=  -31147.781150
 From last iter    ehf=  -31147.781170   ehk=  -31147.781162
 diffe(q)=  0.000014 (0.000322)    tol= 0.000010 (0.000100)   more=T
i nk=8 ehf=-31147.7811554 ehk=-31147.7811496

 --- BNDFP:  begin iteration 12 of 80 ---

 Average es pot at rmt = 0.128316  avg sphere pot = 0.241672   vconst = -0.128316
 smooth rhoves      2.672482   charge     4.558252
 smooth rhoeps =   -1.392344   rhomu =   -1.392476  avg vxc =   -0.335280 

 elocp:

 Fit local orbitals to sm hankels, species Cs, rmt=4.939085
  l  type    Pnu      Eval        K.E.       Rsm       Eh      Q(r>rmt)    Fit K.E.
  1  low    5.947   -0.915196   -0.619380   2.33015  -2.30151   0.01412   -0.619380 

 locpot:

 site  1  z= 55.0  rmt= 4.93908  nr=1261  a=0.010  nlml=25  rg=1.235  Vfloat=T
 sm core charge = 0.037439 (sphere) + 0.000473 (spillout) = 0.037912
 potential shift to crystal energy zero:    0.000008

 site  2  z= 55.0  rmt= 4.93908  nr=1261  a=0.010  nlml=25  rg=1.235  Vfloat=T
 sm core charge = 0.037439 (sphere) + 0.000473 (spillout) = 0.037912
 potential shift to crystal energy zero:    0.000008

 Energy terms:             smooth           local            total
   rhoval*vef             -3.189014      -108.681769      -111.870784
   rhoval*ves            -15.316807       -81.117433       -96.434239
   psnuc*ves              20.661770   -126913.616631   -126892.954861
   utot                    2.672482    -63497.367032    -63494.694550
   rho*exc                -1.392344      -768.867204      -770.259549
   rho*vxc                -1.392476     -1003.913861     -1005.306337
   valence chg             4.558252         9.441748        14.000000
   core charge            96.000000         0.000000        96.000000

 Charges:  valence    14.00000   cores    96.00000   nucleii  -110.00000
    hom background     0.00000   deviation from neutrality:      0.00000

 sugcut:  make orbital-dependent cutoffs for local orbitals, tol=1.0e-16
 spec      l    rsm    eh     gmax    last term   cutoff
  Cs       1    2.33  -2.30   5.327    1.19E-16    3959 
 

 Start first of two band passes ...
 bndfp:  kpt 1 of 35, k=  0.00000  0.00000  0.00000
 -0.9191 -0.9191 -0.9191 -0.9122 -0.9122 -0.9122 -0.2550 -0.0843 -0.0843
 bndfp:  kpt 11 of 35, k=  0.37500  0.25000  0.00000
 -0.9207 -0.9189 -0.9166 -0.9144 -0.9144 -0.9125 -0.1824 -0.1160 -0.0650
 bndfp:  kpt 21 of 35, k=  0.37500  0.25000  0.12500
 -0.9205 -0.9191 -0.9172 -0.9145 -0.9140 -0.9127 -0.1770 -0.1109 -0.0638
 bndfp:  kpt 31 of 35, k=  0.50000  0.50000  0.25000
 -0.9204 -0.9204 -0.9168 -0.9156 -0.9136 -0.9136 -0.1037 -0.1036 -0.0696

 BZWTS : --- Tetrahedron Integration ---
 BZINTS: Fermi energy:     -0.131965;  14.000000 electrons;  D(Ef):   42.093
         Sum occ. bands:  -11.3467214  incl. Bloechl correction:   -0.003542

 Saved qp weights ...
 Start second band pass ...
 bndfp:  kpt 1 of 35, k=  0.00000  0.00000  0.00000
 -0.9191 -0.9191 -0.9191 -0.9122 -0.9122 -0.9122 -0.2550 -0.0843 -0.0843
 bndfp:  kpt 11 of 35, k=  0.37500  0.25000  0.00000
 -0.9207 -0.9189 -0.9166 -0.9144 -0.9144 -0.9125 -0.1824 -0.1160 -0.0650
 bndfp:  kpt 21 of 35, k=  0.37500  0.25000  0.12500
 -0.9205 -0.9191 -0.9172 -0.9145 -0.9140 -0.9127 -0.1770 -0.1109 -0.0638
 bndfp:  kpt 31 of 35, k=  0.50000  0.50000  0.25000
 -0.9204 -0.9204 -0.9168 -0.9156 -0.9136 -0.9136 -0.1037 -0.1036 -0.0696

 BZWTS : --- Tetrahedron Integration ---
 BZINTS: Fermi energy:     -0.131965;  14.000000 electrons;  D(Ef):   42.093
         Sum occ. bands:  -11.3467214  incl. Bloechl correction:   -0.003542

 Saved qp weights ...

 mkrout:  Qtrue      sm,loc       local
   1    6.549319    1.821511    4.727808
   2    6.568387    1.854412    4.713975

 Symmetrize density..

 Make new boundary conditions for phi,phidot..

 site    1   species   1:Cs      
 l  idmod     ql         ebar        pold        ptry        pfree        pnew
 0     0    0.381710   -0.184341    6.627598    6.619153    6.500000    6.619153
 1     0    0.122410   -0.175009    6.500000    6.244255    6.250000    6.500000
 1     0    sc         -0.914605    5.946747    5.946741    5.250000   15.946741
 2     0    0.071356   -0.162024    5.289393    5.294177    5.147584    5.294177
 2     0    sc          0.000000    6.300000    6.147584    6.147584    6.300000
 3     0    0.001671   -0.429888    4.121119    4.095529    4.102416    4.121119
 4     0    0.000301   -0.784339    5.088586    5.063315    5.077979    5.088586

 site    2   species   1:Cs      
 l  idmod     ql         ebar        pold        ptry        pfree        pnew
 0     0    0.411892   -0.180589    6.618399    6.627046    6.500000    6.627046
 1     0    0.118339   -0.176482    6.500000    6.243292    6.250000    6.500000
 1     0    sc         -0.915774    5.946761    5.946767    5.250000   15.946767
 2     0    0.063999   -0.165457    5.294743    5.289999    5.147584    5.289999
 2     0    sc          0.000000    6.300000    6.147584    6.147584    6.300000
 3     0    0.001795   -0.409778    4.121119    4.097076    4.102416    4.121119
 4     0    0.000318   -0.766503    5.088586    5.063746    5.077979    5.088586

 Harris energy:
 sumev=      -11.346721  val*vef=    -111.870784   sumtv=     100.524062
 sumec=        0.000000  cor*vef=       0.000000   ttcor=   33016.648880
 rhoeps=    -770.259549     utot=  -63494.694550    ehar=  -31147.781156

 srhov:     -3.188989   -108.682073   -111.871062 sumev=  -11.346721   sumtv=  100.524341

 Kohn-Sham energy:
 sumtv=      100.524341  sumtc=     33016.648880   ekin=    33117.173221
 rhoep=     -770.259579   utot=    -63494.694793   ehks=   -31147.781150
  
 mixing: mode=B  nmix=4  beta=1  elind=.112
 mixrho:  sought 4 iter from file mixm; read 5.  RMS DQ=4.76e-5  last it=3.22e-4
 broyj:  ir=4  dxmax=8e-4  gmax=5.8e-4  wc=1.6
 unscreened rms difference:  smooth  0.000031   local  0.000026
   screened rms difference:  smooth  0.000022   local  0.000026   tot  0.000048

 iors  : write restart file (binary, mesh density)

   it 12  of 80    ehf=  -31147.781156   ehk=  -31147.781150
 From last iter    ehf=  -31147.781155   ehk=  -31147.781150
 diffe(q)= -0.000001 (0.000048)    tol= 0.000010 (0.000100)   more=F
c nk=8 ehf=-31147.7811563 ehk=-31147.7811504
 Exit 0 LMF
 CPU time:  74.180s   Wall clock 74.212s  at  21:14:47 28.04.2019  on  nmscde001136.nms.kcl
rdcmd:  
